// Generated by Haxe 3.4.0
(function ($global) { "use strict";
function $extend(from, fields) {
	function Inherit() {} Inherit.prototype = from; var proto = new Inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var dci_Context = function() { };
dci_Context.__name__ = ["dci","Context"];
var BorrowLibraryItems = function(scanner,cardReader,screen,printer,keypad,finishButtons) {
	this.scanner = scanner;
	this.cardReader = cardReader;
	this.screen = screen;
	this.printer = printer;
	this.keypad = keypad;
	this.finishButtons = finishButtons;
	this.library = Data;
	this.scannedItems = [];
};
BorrowLibraryItems.__name__ = ["BorrowLibraryItems"];
BorrowLibraryItems.__interfaces__ = [dci_Context];
BorrowLibraryItems.prototype = {
	start: function() {
		this.resetState();
		this.screen__displayWelcome();
		this.cardReader__waitForCardChange();
	}
	,restart: function() {
		this.resetState();
		this.screen__displayThankYouMessage();
		this.cardReader__waitForCardChange();
	}
	,resetState: function() {
		if(this.removeCardLoop != null) {
			this.removeCardLoop.stop();
		}
		this.scannedItems__clearItems();
		this.pinAttemptsLeft = BorrowLibraryItems.maxPinAttempts;
		this.authorizedCard = null;
		this.lastScannedRfid = haxe_ds_Option.None;
	}
	,cardReader__waitForCardChange: function() {
		this.cardReader.scanRfid($bind(this,this.cardReader__rfidScanned));
	}
	,cardReader__rfidScanned: function(data) {
		var _gthis = this;
		switch(data[1]) {
		case 0:
			var rfid = data[2];
			this.removeCardLoop = new haxe_Timer(50);
			this.removeCardLoop.run = function() {
				_gthis.cardReader.scanRfid(function(data1) {
					if(Type.enumEq(data1,haxe_ds_Option.None)) {
						_gthis.restart();
					}
				});
			};
			var card = this.library__card(rfid);
			if(card != null) {
				this.keypad__waitForEnterPin();
			} else {
				this.screen__displayInvalidCard();
			}
			break;
		case 1:
			this.cardReader__waitForCardChange();
			break;
		}
	}
	,cardReader__validatePin: function(pin) {
		var _gthis = this;
		this.cardReader.scanRfid(function(data) {
			switch(data[1]) {
			case 0:
				var rfid = data[2];
				var card = _gthis.library__card(rfid);
				if(card == null) {
					_gthis.screen__displayInvalidCard();
				} else if(card.pin == pin) {
					_gthis.authorizedCard = card;
					_gthis.screen__displayScannedItems();
					_gthis.scanner__waitForItem();
				} else if(--_gthis.pinAttemptsLeft > 0) {
					_gthis.keypad__waitForEnterPin();
				} else {
					_gthis.screen__displayTooManyInvalidPin();
				}
				break;
			case 1:
				break;
			}
		});
	}
	,scanner__waitForItem: function() {
		this.scanner.scanRfid($bind(this,this.scanner__rfidScanned));
	}
	,scanner__rfidScanned: function(rfid) {
		if(this.authorizedCard == null) {
			return;
		}
		if(Type.enumEq(rfid,this.lastScannedRfid)) {
			this.scanner__waitForItem();
			return;
		} else {
			this.lastScannedRfid = rfid;
		}
		switch(rfid[1]) {
		case 0:
			var rfid1 = rfid[2];
			if(this.scannedItems__alreadyScanned(rfid1)) {
				this.scanner__waitForItem();
				return;
			}
			var item = this.library__item(rfid1);
			if(item == null) {
				this.scanner__waitForItem();
				return;
			}
			var _g = new BorrowLoanItem(item,this.authorizedCard).borrow();
			switch(_g[1]) {
			case 0:
				var loan = _g[2];
				this.scannedItems__addItem({ item : item, returnDate : loan.returnDate});
				this.screen__displayScannedItems();
				this.scanner__waitForItem();
				break;
			case 1:
				this.screen__displayAlreadyBorrowedMessage();
				this.scanner__waitForItem();
				break;
			case 2:
				this.screen__displayInvalidCard();
				break;
			case 3:
				this.screen__displayInvalidLoanItemMessage();
				this.scanner__waitForItem();
				break;
			}
			break;
		case 1:
			this.scanner__waitForItem();
			break;
		}
	}
	,scannedItems__addItem: function(item) {
		this.scannedItems.push(item);
	}
	,scannedItems__clearItems: function() {
		this.scannedItems.splice(0,this.scannedItems.length);
	}
	,scannedItems__alreadyScanned: function(rfid) {
		return Lambda.exists(this.scannedItems,function(scannedItem) {
			return scannedItem.item.rfid == rfid;
		});
	}
	,screen__displayWelcome: function() {
		this.screen.display(views_ScreenState.Welcome);
	}
	,screen__displayThankYouMessage: function() {
		this.screen.displayMessage(views_ScreenState.ThankYou,4000,views_ScreenState.Welcome);
	}
	,screen__displayEnterPin: function() {
		this.screen.display(views_ScreenState.EnterPin({ previousAttemptFailed : this.pinAttemptsLeft < 3}));
	}
	,screen__displayScannedItems: function() {
		this.finishButtons__waitForFinishClick();
		this.screen.display(views_ScreenState.DisplayBorrowedItems(this.scannedItems));
	}
	,screen__displayTooManyInvalidPin: function() {
		this.screen.display(views_ScreenState.TooManyInvalidPin);
	}
	,screen__displayInvalidCard: function() {
		this.screen.display(views_ScreenState.InvalidCard);
	}
	,screen__displayInvalidLoanItemMessage: function() {
		this.screen.displayMessage(views_ScreenState.InvalidLoanItem,3000);
	}
	,screen__displayAlreadyBorrowedMessage: function() {
		this.screen.displayMessage(views_ScreenState.ItemAlreadyBorrowed,3000);
	}
	,screen__displayDontForgetLibraryCard: function() {
		this.screen.display(views_ScreenState.DontForgetLibraryCard);
	}
	,finishButtons__waitForFinishClick: function() {
		this.finishButtons.onFinishWithoutReceiptClicked($bind(this,this.screen__displayDontForgetLibraryCard),{ fileName : "BorrowLibraryItems.hx", lineNumber : 212, className : "BorrowLibraryItems", methodName : "finishButtons__waitForFinishClick"});
		this.finishButtons.onFinishWithReceiptClicked($bind(this,this.printer__printReceipt),{ fileName : "BorrowLibraryItems.hx", lineNumber : 213, className : "BorrowLibraryItems", methodName : "finishButtons__waitForFinishClick"});
	}
	,keypad__waitForEnterPin: function() {
		this.screen__displayEnterPin();
		this.keypad.onPinCodeEntered($bind(this,this.cardReader__validatePin),{ fileName : "BorrowLibraryItems.hx", lineNumber : 222, className : "BorrowLibraryItems", methodName : "keypad__waitForEnterPin"});
	}
	,printer__printReceipt: function() {
		var _gthis = this;
		var buffer = [DateTools.format(new Date(),"%Y-%m-%d"),""];
		var scanned = $iterator(this.scannedItems)();
		while(scanned.hasNext()) {
			var scanned1 = scanned.next();
			buffer.push(scanned1.item.title);
			var tmp = "Return on " + DateTools.format(scanned1.returnDate,"%Y-%m-%d");
			buffer.push(tmp);
			buffer.push("");
		}
		var timer = new haxe_Timer(100);
		timer.run = function() {
			_gthis.printer.print(buffer.pop());
			if(buffer.length == 0) {
				timer.stop();
				_gthis.printer.cutPaper();
				_gthis.screen__displayDontForgetLibraryCard();
			}
		};
	}
	,library__item: function(rfid) {
		return Lambda.find(this.library.libraryItems,function(loanItem) {
			return loanItem.rfid == rfid;
		});
	}
	,library__card: function(rfid) {
		return Lambda.find(this.library.libraryCards,function(libraryCard) {
			return libraryCard.rfid == rfid;
		});
	}
	,__class__: BorrowLibraryItems
};
var BorrowLoanItemStatus = { __ename__ : true, __constructs__ : ["Ok","ItemAlreadyBorrowed","InvalidBorrower","InvalidLoanItem"] };
BorrowLoanItemStatus.Ok = function(loan) { var $x = ["Ok",0,loan]; $x.__enum__ = BorrowLoanItemStatus; return $x; };
BorrowLoanItemStatus.ItemAlreadyBorrowed = ["ItemAlreadyBorrowed",1];
BorrowLoanItemStatus.ItemAlreadyBorrowed.__enum__ = BorrowLoanItemStatus;
BorrowLoanItemStatus.InvalidBorrower = ["InvalidBorrower",2];
BorrowLoanItemStatus.InvalidBorrower.__enum__ = BorrowLoanItemStatus;
BorrowLoanItemStatus.InvalidLoanItem = ["InvalidLoanItem",3];
BorrowLoanItemStatus.InvalidLoanItem.__enum__ = BorrowLoanItemStatus;
var BorrowLoanItem = function(loanItem,borrower) {
	this.listOfLibraryCards = Data.libraryCards;
	this.listOfItems = Data.libraryItems;
	this.listOfLoans = Data.libraryLoans;
	this.loanItem = loanItem;
	this.borrower = borrower;
};
BorrowLoanItem.__name__ = ["BorrowLoanItem"];
BorrowLoanItem.__interfaces__ = [dci_Context];
BorrowLoanItem.prototype = {
	borrow: function() {
		if(!this.listOfItems__hasLoanItem()) {
			return BorrowLoanItemStatus.InvalidLoanItem;
		} else if(!this.listOfLibraryCards__hasBorrowerID()) {
			return BorrowLoanItemStatus.InvalidBorrower;
		} else if(this.listOfLoans__hasBorrowedLoanItem()) {
			return BorrowLoanItemStatus.ItemAlreadyBorrowed;
		} else {
			var loan = new LibraryLoan({ borrowerRfid : this.borrower__id(), loanItemRfid : this.loanItem__id(), created : new Date(), returnDate : this.loanItem__returnDateFromToday()});
			this.listOfLoans__addLoan(loan);
			return BorrowLoanItemStatus.Ok(loan);
		}
	}
	,listOfLoans__hasBorrowedLoanItem: function() {
		var _gthis = this;
		return Lambda.exists(this.listOfLoans,function(loan) {
			if(loan.loanItemRfid == _gthis.loanItem__id()) {
				return loan.returnDate.getTime() > new Date().getTime();
			} else {
				return false;
			}
		});
	}
	,listOfLoans__addLoan: function(loan) {
		this.listOfLoans.push(loan);
	}
	,listOfLibraryCards__hasBorrowerID: function() {
		var _gthis = this;
		return Lambda.exists(this.listOfLibraryCards,function(card) {
			return card.rfid == _gthis.borrower__id();
		});
	}
	,listOfItems__hasLoanItem: function() {
		var _gthis = this;
		return Lambda.exists(this.listOfItems,function(item) {
			return item.rfid == _gthis.loanItem__id();
		});
	}
	,loanItem__id: function() {
		return this.loanItem.rfid;
	}
	,loanItem__returnDateFromToday: function() {
		var t = new Date().getTime() + this.loanItem.loanTimeDays * 24 * 60 * 60 * 1000;
		return new Date(t);
	}
	,borrower__id: function() {
		return this.borrower.rfid;
	}
	,__class__: BorrowLoanItem
};
var Data = function() { };
Data.__name__ = ["Data"];
var RfidItem = function() { };
RfidItem.__name__ = ["RfidItem"];
RfidItem.prototype = {
	__class__: RfidItem
};
var DragDropItem = function() { };
DragDropItem.__name__ = ["DragDropItem"];
var LoanItem = function() { };
LoanItem.__name__ = ["LoanItem"];
LoanItem.__interfaces__ = [RfidItem,DragDropItem];
LoanItem.prototype = {
	__class__: LoanItem
};
var DataClass = function() { };
DataClass.__name__ = ["DataClass"];
var haxecontracts_HaxeContracts = function() { };
haxecontracts_HaxeContracts.__name__ = ["haxecontracts","HaxeContracts"];
var Book = function(data) {
	this.set_rfid(data.rfid);
	this.set_title(data.title);
	this.set_loanTimeDays(data.loanTimeDays);
};
Book.__name__ = ["Book"];
Book.__interfaces__ = [LoanItem,DataClass,haxecontracts_HaxeContracts];
Book.validate = function(data) {
	var output = [];
	if(!Object.prototype.hasOwnProperty.call(data,"rfid")) {
		output.push("rfid");
	} else if(data.rfid == null || data.rfid.length <= 0) {
		output.push("rfid");
	}
	if(!Object.prototype.hasOwnProperty.call(data,"title")) {
		output.push("title");
	} else if(data.title == null || data.title.length <= 0) {
		output.push("title");
	}
	if(!Object.prototype.hasOwnProperty.call(data,"loanTimeDays")) {
		output.push("loanTimeDays");
	} else if(data.loanTimeDays == null || data.loanTimeDays <= 0) {
		output.push("loanTimeDays");
	}
	return output;
};
Book.prototype = {
	set_rfid: function(v) {
		if(v == null || v.length <= 0) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("DataClass validation failed for Book.rfid.",this,null,v,{ fileName : "Builder.hx", lineNumber : 245, className : "Book", methodName : "set_rfid"}));
		}
		return this.rfid = v;
	}
	,set_title: function(v) {
		if(v == null || v.length <= 0) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("DataClass validation failed for Book.title.",this,null,v,{ fileName : "Builder.hx", lineNumber : 245, className : "Book", methodName : "set_title"}));
		}
		return this.title = v;
	}
	,set_loanTimeDays: function(v) {
		if(v == null || v <= 0) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("DataClass validation failed for Book.loanTimeDays.",this,null,v,{ fileName : "Builder.hx", lineNumber : 245, className : "Book", methodName : "set_loanTimeDays"}));
		}
		return this.loanTimeDays = v;
	}
	,__class__: Book
};
var Bluray = function(data) {
	this.set_rfid(data.rfid);
	this.set_title(data.title);
	this.set_length(data.length);
	this.set_loanTimeDays(data.loanTimeDays);
};
Bluray.__name__ = ["Bluray"];
Bluray.__interfaces__ = [LoanItem,DataClass,haxecontracts_HaxeContracts];
Bluray.validate = function(data) {
	var output = [];
	if(!Object.prototype.hasOwnProperty.call(data,"rfid")) {
		output.push("rfid");
	} else if(data.rfid == null || data.rfid.length <= 0) {
		output.push("rfid");
	}
	if(!Object.prototype.hasOwnProperty.call(data,"title")) {
		output.push("title");
	} else if(data.title == null || data.title.length <= 0) {
		output.push("title");
	}
	if(!Object.prototype.hasOwnProperty.call(data,"length")) {
		output.push("length");
	} else if(data.length == null || data.length <= 0) {
		output.push("length");
	}
	if(!Object.prototype.hasOwnProperty.call(data,"loanTimeDays")) {
		output.push("loanTimeDays");
	} else if(data.loanTimeDays == null || data.loanTimeDays <= 0) {
		output.push("loanTimeDays");
	}
	return output;
};
Bluray.prototype = {
	set_rfid: function(v) {
		if(v == null || v.length <= 0) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("DataClass validation failed for Bluray.rfid.",this,null,v,{ fileName : "Builder.hx", lineNumber : 245, className : "Bluray", methodName : "set_rfid"}));
		}
		return this.rfid = v;
	}
	,set_title: function(v) {
		if(v == null || v.length <= 0) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("DataClass validation failed for Bluray.title.",this,null,v,{ fileName : "Builder.hx", lineNumber : 245, className : "Bluray", methodName : "set_title"}));
		}
		return this.title = v;
	}
	,set_length: function(v) {
		if(v == null || v <= 0) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("DataClass validation failed for Bluray.length.",this,null,v,{ fileName : "Builder.hx", lineNumber : 245, className : "Bluray", methodName : "set_length"}));
		}
		return this.length = v;
	}
	,set_loanTimeDays: function(v) {
		if(v == null || v <= 0) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("DataClass validation failed for Bluray.loanTimeDays.",this,null,v,{ fileName : "Builder.hx", lineNumber : 245, className : "Bluray", methodName : "set_loanTimeDays"}));
		}
		return this.loanTimeDays = v;
	}
	,__class__: Bluray
};
var Card = function(data) {
	this.set_rfid(data.rfid);
	this.set_name(data.name);
	this.set_pin(data.pin);
};
Card.__name__ = ["Card"];
Card.__interfaces__ = [RfidItem,DragDropItem,DataClass,haxecontracts_HaxeContracts];
Card.validate = function(data) {
	var output = [];
	if(!Object.prototype.hasOwnProperty.call(data,"rfid")) {
		output.push("rfid");
	} else if(data.rfid == null || data.rfid.length <= 0) {
		output.push("rfid");
	}
	if(!Object.prototype.hasOwnProperty.call(data,"name")) {
		output.push("name");
	} else if(data.name == null || data.name.length <= 0) {
		output.push("name");
	}
	if(!Object.prototype.hasOwnProperty.call(data,"pin")) {
		output.push("pin");
	} else if(data.pin == null || !new EReg("^\\d{4}$","").match(data.pin)) {
		output.push("pin");
	}
	return output;
};
Card.prototype = {
	set_rfid: function(v) {
		if(v == null || v.length <= 0) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("DataClass validation failed for Card.rfid.",this,null,v,{ fileName : "Builder.hx", lineNumber : 245, className : "Card", methodName : "set_rfid"}));
		}
		return this.rfid = v;
	}
	,set_name: function(v) {
		if(v == null || v.length <= 0) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("DataClass validation failed for Card.name.",this,null,v,{ fileName : "Builder.hx", lineNumber : 245, className : "Card", methodName : "set_name"}));
		}
		return this.name = v;
	}
	,set_pin: function(v) {
		if(v == null || !new EReg("^\\d{4}$","").match(v)) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("DataClass validation failed for Card.pin.",this,null,v,{ fileName : "Builder.hx", lineNumber : 245, className : "Card", methodName : "set_pin"}));
		}
		return this.pin = v;
	}
	,__class__: Card
};
var LibraryLoan = function(data) {
	this.set_loanItemRfid(data.loanItemRfid);
	this.set_borrowerRfid(data.borrowerRfid);
	this.set_created(data.created);
	this.set_returnDate(data.returnDate);
};
LibraryLoan.__name__ = ["LibraryLoan"];
LibraryLoan.__interfaces__ = [DataClass,haxecontracts_HaxeContracts];
LibraryLoan.validate = function(data) {
	var output = [];
	if(!Object.prototype.hasOwnProperty.call(data,"loanItemRfid")) {
		output.push("loanItemRfid");
	} else if(data.loanItemRfid == null || data.loanItemRfid.length <= 0) {
		output.push("loanItemRfid");
	}
	if(!Object.prototype.hasOwnProperty.call(data,"borrowerRfid")) {
		output.push("borrowerRfid");
	} else if(data.borrowerRfid == null || data.borrowerRfid.length <= 0) {
		output.push("borrowerRfid");
	}
	if(!Object.prototype.hasOwnProperty.call(data,"created")) {
		output.push("created");
	} else if(data.created == null) {
		output.push("created");
	}
	if(!Object.prototype.hasOwnProperty.call(data,"returnDate")) {
		output.push("returnDate");
	} else if(data.returnDate == null) {
		output.push("returnDate");
	}
	return output;
};
LibraryLoan.prototype = {
	set_loanItemRfid: function(v) {
		if(v == null || v.length <= 0) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("DataClass validation failed for LibraryLoan.loanItemRfid.",this,null,v,{ fileName : "Builder.hx", lineNumber : 245, className : "LibraryLoan", methodName : "set_loanItemRfid"}));
		}
		return this.loanItemRfid = v;
	}
	,set_borrowerRfid: function(v) {
		if(v == null || v.length <= 0) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("DataClass validation failed for LibraryLoan.borrowerRfid.",this,null,v,{ fileName : "Builder.hx", lineNumber : 245, className : "LibraryLoan", methodName : "set_borrowerRfid"}));
		}
		return this.borrowerRfid = v;
	}
	,set_created: function(v) {
		if(v == null) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("DataClass validation failed for LibraryLoan.created.",this,null,v,{ fileName : "Builder.hx", lineNumber : 245, className : "LibraryLoan", methodName : "set_created"}));
		}
		return this.created = v;
	}
	,set_returnDate: function(v) {
		if(v == null) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("DataClass validation failed for LibraryLoan.returnDate.",this,null,v,{ fileName : "Builder.hx", lineNumber : 245, className : "LibraryLoan", methodName : "set_returnDate"}));
		}
		return this.returnDate = v;
	}
	,__class__: LibraryLoan
};
var DateTools = function() { };
DateTools.__name__ = ["DateTools"];
DateTools.__format_get = function(d,e) {
	switch(e) {
	case "%":
		return "%";
	case "A":
		return DateTools.DAY_NAMES[d.getDay()];
	case "B":
		return DateTools.MONTH_NAMES[d.getMonth()];
	case "C":
		return StringTools.lpad(Std.string(d.getFullYear() / 100 | 0),"0",2);
	case "D":
		return DateTools.__format(d,"%m/%d/%y");
	case "F":
		return DateTools.__format(d,"%Y-%m-%d");
	case "I":case "l":
		var hour = d.getHours() % 12;
		return StringTools.lpad(Std.string(hour == 0 ? 12 : hour),e == "I" ? "0" : " ",2);
	case "M":
		return StringTools.lpad(Std.string(d.getMinutes()),"0",2);
	case "R":
		return DateTools.__format(d,"%H:%M");
	case "S":
		return StringTools.lpad(Std.string(d.getSeconds()),"0",2);
	case "T":
		return DateTools.__format(d,"%H:%M:%S");
	case "Y":
		return Std.string(d.getFullYear());
	case "a":
		return DateTools.DAY_SHORT_NAMES[d.getDay()];
	case "b":case "h":
		return DateTools.MONTH_SHORT_NAMES[d.getMonth()];
	case "d":
		return StringTools.lpad(Std.string(d.getDate()),"0",2);
	case "e":
		return Std.string(d.getDate());
	case "H":case "k":
		return StringTools.lpad(Std.string(d.getHours()),e == "H" ? "0" : " ",2);
	case "m":
		return StringTools.lpad(Std.string(d.getMonth() + 1),"0",2);
	case "n":
		return "\n";
	case "p":
		if(d.getHours() > 11) {
			return "PM";
		} else {
			return "AM";
		}
		break;
	case "r":
		return DateTools.__format(d,"%I:%M:%S %p");
	case "s":
		return Std.string(d.getTime() / 1000 | 0);
	case "t":
		return "\t";
	case "u":
		var t = d.getDay();
		if(t == 0) {
			return "7";
		} else if(t == null) {
			return "null";
		} else {
			return "" + t;
		}
		break;
	case "w":
		return Std.string(d.getDay());
	case "y":
		return StringTools.lpad(Std.string(d.getFullYear() % 100),"0",2);
	default:
		throw new js__$Boot_HaxeError("Date.format %" + e + "- not implemented yet.");
	}
};
DateTools.__format = function(d,f) {
	var r_b = "";
	var p = 0;
	while(true) {
		var np = f.indexOf("%",p);
		if(np < 0) {
			break;
		}
		var len = np - p;
		r_b += len == null ? HxOverrides.substr(f,p,null) : HxOverrides.substr(f,p,len);
		r_b += Std.string(DateTools.__format_get(d,HxOverrides.substr(f,np + 1,1)));
		p = np + 2;
	}
	var len1 = f.length - p;
	r_b += len1 == null ? HxOverrides.substr(f,p,null) : HxOverrides.substr(f,p,len1);
	return r_b;
};
DateTools.format = function(d,f) {
	return DateTools.__format(d,f);
};
var DragDrop = function(surfaces) {
	try {
		if(surfaces == null) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [surfaces != null]",this,[surfaces],null,{ fileName : "DragDrop.hx", lineNumber : 38, className : "DragDrop", methodName : "new"}));
		}
	} catch( e ) {
		if (e instanceof js__$Boot_HaxeError) e = e.val;
		throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [surfaces != null]",this,[surfaces],e,{ fileName : "DragDrop.hx", lineNumber : 38, className : "DragDrop", methodName : "new"}));
	}
	this.surfaces = surfaces;
};
DragDrop.__name__ = ["DragDrop"];
DragDrop.__interfaces__ = [haxecontracts_HaxeContracts];
DragDrop.prototype = {
	start: function() {
		try {
			if(Reflect.field(window,"dragula") == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [Reflect.field(Browser.window, \"dragula\") != null]",this,[],null,{ fileName : "DragDrop.hx", lineNumber : 43, className : "DragDrop", methodName : "start"}));
			}
		} catch( e ) {
			if (e instanceof js__$Boot_HaxeError) e = e.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [Reflect.field(Browser.window, \"dragula\") != null]",this,[],e,{ fileName : "DragDrop.hx", lineNumber : 43, className : "DragDrop", methodName : "start"}));
		}
		var dragula = Reflect.field(window,"dragula");
		var _g = [];
		var id = this.surfaces.keys();
		while(id.hasNext()) {
			var id1 = id.next();
			_g.push(HtmlTools.q("#" + id1));
		}
		this.drake = dragula(_g,{ accepts : $bind(this,this.acceptsDrop)}).on("drag",$bind(this,this.onDrag)).on("drop",$bind(this,this.onDrop));
		console.log("Drag'n'drop interface enabled.");
	}
	,acceptsDrop: function(droppedItem,targetElement) {
		try {
			if(droppedItem == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [droppedItem != null]",this,[droppedItem,targetElement],null,{ fileName : "DragDrop.hx", lineNumber : 58, className : "DragDrop", methodName : "acceptsDrop"}));
			}
		} catch( e ) {
			if (e instanceof js__$Boot_HaxeError) e = e.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [droppedItem != null]",this,[droppedItem,targetElement],e,{ fileName : "DragDrop.hx", lineNumber : 58, className : "DragDrop", methodName : "acceptsDrop"}));
		}
		try {
			if(targetElement.id.length <= 0) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [targetElement.id.length > 0]",this,[droppedItem,targetElement],null,{ fileName : "DragDrop.hx", lineNumber : 59, className : "DragDrop", methodName : "acceptsDrop"}));
			}
		} catch( e1 ) {
			if (e1 instanceof js__$Boot_HaxeError) e1 = e1.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [targetElement.id.length > 0]",this,[droppedItem,targetElement],e1,{ fileName : "DragDrop.hx", lineNumber : 59, className : "DragDrop", methodName : "acceptsDrop"}));
		}
		var _g = targetElement.id;
		switch(_g) {
		case "card-reader":case "scanner":
			if(this.surfaces.get(targetElement.id).length == 1) {
				return false;
			}
			break;
		default:
		}
		var _g1 = droppedItem.id;
		if(_g1 == "card") {
			return targetElement.id != "bookshelf";
		} else {
			return targetElement.id != "card-reader";
		}
	}
	,onDrag: function(el,sourceEl) {
		try {
			if(el == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [el != null]",this,[el,sourceEl],null,{ fileName : "DragDrop.hx", lineNumber : 82, className : "DragDrop", methodName : "onDrag"}));
			}
		} catch( e ) {
			if (e instanceof js__$Boot_HaxeError) e = e.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [el != null]",this,[el,sourceEl],e,{ fileName : "DragDrop.hx", lineNumber : 82, className : "DragDrop", methodName : "onDrag"}));
		}
		try {
			var key = sourceEl.id;
			var _this = this.surfaces;
			if(!(__map_reserved[key] != null ? _this.existsReserved(key) : _this.h.hasOwnProperty(key))) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("No surface found: " + sourceEl.id,this,[el,sourceEl],null,{ fileName : "DragDrop.hx", lineNumber : 83, className : "DragDrop", methodName : "onDrag"}));
			}
		} catch( e1 ) {
			if (e1 instanceof js__$Boot_HaxeError) e1 = e1.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("No surface found: " + sourceEl.id,this,[el,sourceEl],e1,{ fileName : "DragDrop.hx", lineNumber : 83, className : "DragDrop", methodName : "onDrag"}));
		}
		var key1 = sourceEl.id;
		var _this1 = this.surfaces;
		var surface = __map_reserved[key1] != null ? _this1.getReserved(key1) : _this1.h[key1];
		var pos = HtmlTools.elPos(sourceEl.children,el);
		try {
			if(pos < 0) {
				throw new js__$Boot_HaxeError(false);
			}
		} catch( e2 ) {
			if (e2 instanceof js__$Boot_HaxeError) e2 = e2.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Item not found in surface " + sourceEl.id,this,null,typeof(e2) == "boolean" ? null : e2,{ fileName : "DragDrop.hx", lineNumber : 87, className : "DragDrop", methodName : "onDrag"}));
		}
		this.dragData = { source : surface, sourcePos : pos};
	}
	,onDrop: function(el,targetEl,_,sibling) {
		try {
			if(this.dragData == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [dragData != null]",this,[el,targetEl,_,sibling],null,{ fileName : "DragDrop.hx", lineNumber : 98, className : "DragDrop", methodName : "onDrop"}));
			}
		} catch( e ) {
			if (e instanceof js__$Boot_HaxeError) e = e.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [dragData != null]",this,[el,targetEl,_,sibling],e,{ fileName : "DragDrop.hx", lineNumber : 98, className : "DragDrop", methodName : "onDrop"}));
		}
		try {
			if(el == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [el != null]",this,[el,targetEl,_,sibling],null,{ fileName : "DragDrop.hx", lineNumber : 99, className : "DragDrop", methodName : "onDrop"}));
			}
		} catch( e1 ) {
			if (e1 instanceof js__$Boot_HaxeError) e1 = e1.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [el != null]",this,[el,targetEl,_,sibling],e1,{ fileName : "DragDrop.hx", lineNumber : 99, className : "DragDrop", methodName : "onDrop"}));
		}
		try {
			var key = targetEl.id;
			var _this = this.surfaces;
			if(!(__map_reserved[key] != null ? _this.existsReserved(key) : _this.h.hasOwnProperty(key))) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("No surface found: " + targetEl.id,this,[el,targetEl,_,sibling],null,{ fileName : "DragDrop.hx", lineNumber : 100, className : "DragDrop", methodName : "onDrop"}));
			}
		} catch( e2 ) {
			if (e2 instanceof js__$Boot_HaxeError) e2 = e2.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("No surface found: " + targetEl.id,this,[el,targetEl,_,sibling],e2,{ fileName : "DragDrop.hx", lineNumber : 100, className : "DragDrop", methodName : "onDrop"}));
		}
		var key1 = targetEl.id;
		var _this1 = this.surfaces;
		var target = __map_reserved[key1] != null ? _this1.getReserved(key1) : _this1.h[key1];
		var targetPos = sibling == null ? targetEl.children.length - 1 : HtmlTools.elPos(targetEl.children,sibling) - 1;
		var removed = this.dragData.source.splice(this.dragData.sourcePos,1);
		target.splice(targetPos,0,removed[0]);
		this.drake.cancel(true);
		m.redraw();
	}
	,__class__: DragDrop
};
var EReg = function(r,opt) {
	this.r = new RegExp(r,opt.split("u").join(""));
};
EReg.__name__ = ["EReg"];
EReg.prototype = {
	match: function(s) {
		if(this.r.global) {
			this.r.lastIndex = 0;
		}
		this.r.m = this.r.exec(s);
		this.r.s = s;
		return this.r.m != null;
	}
	,matched: function(n) {
		if(this.r.m != null && n >= 0 && n < this.r.m.length) {
			return this.r.m[n];
		} else {
			throw new js__$Boot_HaxeError("EReg::matched");
		}
	}
	,__class__: EReg
};
var _$HtmlElements_HtmlElements_$Impl_$ = {};
_$HtmlElements_HtmlElements_$Impl_$.__name__ = ["_HtmlElements","HtmlElements_Impl_"];
_$HtmlElements_HtmlElements_$Impl_$.toElement = function(this1) {
	return window.document.querySelector("#" + this1);
};
var HtmlTools = function() { };
HtmlTools.__name__ = ["HtmlTools"];
HtmlTools.q = function(query) {
	return window.document.querySelector(query);
};
HtmlTools.elPos = function(collection,el) {
	var _g1 = 0;
	var _g = collection.length;
	while(_g1 < _g) {
		var i = _g1++;
		if(collection.item(i) == el) {
			return i;
		}
	}
	return -1;
};
var HxOverrides = function() { };
HxOverrides.__name__ = ["HxOverrides"];
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) {
		return undefined;
	}
	return x;
};
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var Lambda = function() { };
Lambda.__name__ = ["Lambda"];
Lambda.array = function(it) {
	var a = [];
	var i = $iterator(it)();
	while(i.hasNext()) {
		var i1 = i.next();
		a.push(i1);
	}
	return a;
};
Lambda.exists = function(it,f) {
	var x = $iterator(it)();
	while(x.hasNext()) {
		var x1 = x.next();
		if(f(x1)) {
			return true;
		}
	}
	return false;
};
Lambda.find = function(it,f) {
	var v = $iterator(it)();
	while(v.hasNext()) {
		var v1 = v.next();
		if(f(v1)) {
			return v1;
		}
	}
	return null;
};
var Main = function() {
};
Main.__name__ = ["Main"];
Main.__interfaces__ = [haxecontracts_HaxeContracts];
Main.main = function() {
	new Main().start();
};
Main.prototype = {
	start: function() {
		Data.libraryItems = [new Book({ rfid : "ITEM787", title : "Anna Karenina", loanTimeDays : 21}),new Bluray({ rfid : "ITEM788", title : "War and Peace", loanTimeDays : 14, length : 168}),new Book({ rfid : "ITEM789", title : "Master and Man", loanTimeDays : 21})];
		Data.libraryCards = [new Card({ rfid : "CARD54321", name : "Leo Tolstoy", pin : "1234"})];
		Data.libraryLoans = [];
		var bookshelf = Lambda.array(Data.libraryItems);
		var workspace = Lambda.array(Data.libraryCards);
		var itemScannerContents = [];
		var itemScanner = new RfidScanner(function() {
			try {
				return haxe_ds_Option.Some((js_Boot.__cast(itemScannerContents[0] , RfidItem)).rfid);
			} catch( e ) {
				return haxe_ds_Option.None;
			}
		});
		var cardReaderContents = [];
		var cardReader = new RfidScanner(function() {
			try {
				return haxe_ds_Option.Some((js_Boot.__cast(cardReaderContents[0] , RfidItem)).rfid);
			} catch( e1 ) {
				return haxe_ds_Option.None;
			}
		});
		var screen = new views_ScreenView(views_ScreenState.Welcome);
		var printer = new ReceiptPrinter();
		new views_MainView(bookshelf,cardReaderContents,workspace,itemScannerContents,screen,printer).mount();
		var _g = new haxe_ds_StringMap();
		var key = "bookshelf";
		if(__map_reserved[key] != null) {
			_g.setReserved(key,bookshelf);
		} else {
			_g.h[key] = bookshelf;
		}
		var key1 = "card-reader";
		if(__map_reserved[key1] != null) {
			_g.setReserved(key1,cardReaderContents);
		} else {
			_g.h[key1] = cardReaderContents;
		}
		var key2 = "workspace";
		if(__map_reserved[key2] != null) {
			_g.setReserved(key2,workspace);
		} else {
			_g.h[key2] = workspace;
		}
		var key3 = "scanner";
		if(__map_reserved[key3] != null) {
			_g.setReserved(key3,itemScannerContents);
		} else {
			_g.h[key3] = itemScannerContents;
		}
		var surfaces = _g;
		new DragDrop(surfaces).start();
		new BorrowLibraryItems(itemScanner,cardReader,screen,printer,screen,screen).start();
	}
	,__class__: Main
};
Math.__name__ = ["Math"];
var mithril_Mithril = function() { };
mithril_Mithril.__name__ = ["mithril","Mithril"];
var ReceiptPrinter = function() {
	this._buffer = [];
	this.paperIsCut = false;
};
ReceiptPrinter.__name__ = ["ReceiptPrinter"];
ReceiptPrinter.__interfaces__ = [mithril_Mithril,haxecontracts_HaxeContracts];
ReceiptPrinter.prototype = {
	get_receipt: function() {
		return this._buffer;
	}
	,print: function(line) {
		if(this.paperIsCut) {
			this._buffer = [];
			this.paperIsCut = false;
		}
		this._buffer.unshift(line);
		m.redraw();
		try {
			if(this._buffer == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [_buffer != null]",this,[line],null,{ fileName : "ReceiptPrinter.hx", lineNumber : 36, className : "ReceiptPrinter", methodName : "print"}));
			}
		} catch( e ) {
			if (e instanceof js__$Boot_HaxeError) e = e.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [_buffer != null]",this,[line],e,{ fileName : "ReceiptPrinter.hx", lineNumber : 36, className : "ReceiptPrinter", methodName : "print"}));
		}
	}
	,cutPaper: function() {
		this.paperIsCut = true;
		try {
			if(this._buffer == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [_buffer != null]",this,[],null,{ fileName : "ReceiptPrinter.hx", lineNumber : 36, className : "ReceiptPrinter", methodName : "cutPaper"}));
			}
		} catch( e ) {
			if (e instanceof js__$Boot_HaxeError) e = e.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [_buffer != null]",this,[],e,{ fileName : "ReceiptPrinter.hx", lineNumber : 36, className : "ReceiptPrinter", methodName : "cutPaper"}));
		}
	}
	,view: function() {
		if(arguments.length > 0 && arguments[0].tag != this) return arguments[0].tag.view.apply(arguments[0].tag, arguments);
		try {
			if(this._buffer == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [_buffer != null]",this,[],null,{ fileName : "ReceiptPrinter.hx", lineNumber : 36, className : "ReceiptPrinter", methodName : "view"}));
			}
		} catch( e ) {
			if (e instanceof js__$Boot_HaxeError) e = e.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [_buffer != null]",this,[],e,{ fileName : "ReceiptPrinter.hx", lineNumber : 36, className : "ReceiptPrinter", methodName : "view"}));
		}
		var _g7 = [];
		var s = $iterator(this.get_receipt())();
		while(s.hasNext()) {
			var s1 = s.next();
			_g7.push(m.m("p",s1 == "" ? m.trust("&nbsp;") : s1));
		}
		var __contract_output = m.m(".box",m.m(".slot",m.m(".paper",_g7)));
		return __contract_output;
	}
	,__class__: ReceiptPrinter
};
var Reflect = function() { };
Reflect.__name__ = ["Reflect"];
Reflect.field = function(o,field) {
	try {
		return o[field];
	} catch( e ) {
		return null;
	}
};
var RfidScanner = function(returnRfid) {
	this.returnRfid = returnRfid;
	this.lastScanned = haxe_ds_Option.None;
	try {
		if(this.lastScanned == null) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [lastScanned != null]",this,[returnRfid],null,{ fileName : "RfidScanner.hx", lineNumber : 43, className : "RfidScanner", methodName : "new"}));
		}
	} catch( e ) {
		if (e instanceof js__$Boot_HaxeError) e = e.val;
		throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [lastScanned != null]",this,[returnRfid],e,{ fileName : "RfidScanner.hx", lineNumber : 43, className : "RfidScanner", methodName : "new"}));
	}
	try {
		if(returnRfid == null) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [returnRfid != null]",this,[returnRfid],null,{ fileName : "RfidScanner.hx", lineNumber : 42, className : "RfidScanner", methodName : "new"}));
		}
	} catch( e1 ) {
		if (e1 instanceof js__$Boot_HaxeError) e1 = e1.val;
		throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [returnRfid != null]",this,[returnRfid],e1,{ fileName : "RfidScanner.hx", lineNumber : 42, className : "RfidScanner", methodName : "new"}));
	}
};
RfidScanner.__name__ = ["RfidScanner"];
RfidScanner.__interfaces__ = [haxecontracts_HaxeContracts];
RfidScanner.prototype = {
	scanRfid: function(callback) {
		var _gthis = this;
		haxe_Timer.delay(function() {
			var scanned = _gthis.returnRfid();
			callback(scanned);
			_gthis.lastScanned = scanned;
		},0);
		try {
			if(this.lastScanned == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [lastScanned != null]",this,[callback],null,{ fileName : "RfidScanner.hx", lineNumber : 43, className : "RfidScanner", methodName : "scanRfid"}));
			}
		} catch( e ) {
			if (e instanceof js__$Boot_HaxeError) e = e.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [lastScanned != null]",this,[callback],e,{ fileName : "RfidScanner.hx", lineNumber : 43, className : "RfidScanner", methodName : "scanRfid"}));
		}
		try {
			if(this.returnRfid == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [returnRfid != null]",this,[callback],null,{ fileName : "RfidScanner.hx", lineNumber : 42, className : "RfidScanner", methodName : "scanRfid"}));
			}
		} catch( e1 ) {
			if (e1 instanceof js__$Boot_HaxeError) e1 = e1.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [returnRfid != null]",this,[callback],e1,{ fileName : "RfidScanner.hx", lineNumber : 42, className : "RfidScanner", methodName : "scanRfid"}));
		}
	}
	,lastScannedRfid: function() {
		try {
			if(this.lastScanned == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [lastScanned != null]",this,[],null,{ fileName : "RfidScanner.hx", lineNumber : 43, className : "RfidScanner", methodName : "lastScannedRfid"}));
			}
		} catch( e ) {
			if (e instanceof js__$Boot_HaxeError) e = e.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [lastScanned != null]",this,[],e,{ fileName : "RfidScanner.hx", lineNumber : 43, className : "RfidScanner", methodName : "lastScannedRfid"}));
		}
		try {
			if(this.returnRfid == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [returnRfid != null]",this,[],null,{ fileName : "RfidScanner.hx", lineNumber : 42, className : "RfidScanner", methodName : "lastScannedRfid"}));
			}
		} catch( e1 ) {
			if (e1 instanceof js__$Boot_HaxeError) e1 = e1.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [returnRfid != null]",this,[],e1,{ fileName : "RfidScanner.hx", lineNumber : 42, className : "RfidScanner", methodName : "lastScannedRfid"}));
		}
		var __contract_output = this.lastScanned;
		return __contract_output;
	}
	,__class__: RfidScanner
};
var SingleEventHandler = function() {
};
SingleEventHandler.__name__ = ["SingleEventHandler"];
SingleEventHandler.__interfaces__ = [haxecontracts_HaxeContracts];
SingleEventHandler.prototype = {
	get_trigger: function() {
		try {
			if(this._trigger == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException(this.removePos != null ? "Event removed before triggered, at " + this.posStr(this.removePos) : this.setPos != null ? "Event already triggered. Set at " + this.posStr(this.setPos) : "Event not set.",this,[],null,{ fileName : "SingleEventHandler.hx", lineNumber : 25, className : "SingleEventHandler", methodName : "get_trigger"}));
			}
		} catch( e ) {
			if (e instanceof js__$Boot_HaxeError) e = e.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException(this.removePos != null ? "Event removed before triggered, at " + this.posStr(this.removePos) : this.setPos != null ? "Event already triggered. Set at " + this.posStr(this.setPos) : "Event not set.",this,[],e,{ fileName : "SingleEventHandler.hx", lineNumber : 25, className : "SingleEventHandler", methodName : "get_trigger"}));
		}
		var t = this._trigger;
		this._trigger = null;
		return t;
	}
	,set: function(event,pos) {
		try {
			if(event == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [event != null]",this,[event,pos],null,{ fileName : "SingleEventHandler.hx", lineNumber : 36, className : "SingleEventHandler", methodName : "set"}));
			}
		} catch( e ) {
			if (e instanceof js__$Boot_HaxeError) e = e.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [event != null]",this,[event,pos],e,{ fileName : "SingleEventHandler.hx", lineNumber : 36, className : "SingleEventHandler", methodName : "set"}));
		}
		try {
			if(!(this._trigger == null || this._trigger == event)) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Event already set at " + this.posStr(this.setPos) + " (Attempted to set at " + this.posStr(pos) + ")",this,[event,pos],null,{ fileName : "SingleEventHandler.hx", lineNumber : 38, className : "SingleEventHandler", methodName : "set"}));
			}
		} catch( e1 ) {
			if (e1 instanceof js__$Boot_HaxeError) e1 = e1.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Event already set at " + this.posStr(this.setPos) + " (Attempted to set at " + this.posStr(pos) + ")",this,[event,pos],e1,{ fileName : "SingleEventHandler.hx", lineNumber : 38, className : "SingleEventHandler", methodName : "set"}));
		}
		this._trigger = event;
		this.setPos = pos;
		this.removePos = null;
	}
	,remove: function(event,pos) {
		try {
			if(event == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [event != null]",this,[event,pos],null,{ fileName : "SingleEventHandler.hx", lineNumber : 47, className : "SingleEventHandler", methodName : "remove"}));
			}
		} catch( e ) {
			if (e instanceof js__$Boot_HaxeError) e = e.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [event != null]",this,[event,pos],e,{ fileName : "SingleEventHandler.hx", lineNumber : 47, className : "SingleEventHandler", methodName : "remove"}));
		}
		try {
			if(this._trigger != event) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException(this.setPos == null ? "Event not set before removal. Removed at " + this.posStr(pos) : "Event not same as the one registered at " + this.posStr(this.setPos) + " (Attempted to remove at " + this.posStr(pos) + ")",this,[event,pos],null,{ fileName : "SingleEventHandler.hx", lineNumber : 49, className : "SingleEventHandler", methodName : "remove"}));
			}
		} catch( e1 ) {
			if (e1 instanceof js__$Boot_HaxeError) e1 = e1.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException(this.setPos == null ? "Event not set before removal. Removed at " + this.posStr(pos) : "Event not same as the one registered at " + this.posStr(this.setPos) + " (Attempted to remove at " + this.posStr(pos) + ")",this,[event,pos],e1,{ fileName : "SingleEventHandler.hx", lineNumber : 49, className : "SingleEventHandler", methodName : "remove"}));
		}
		this._trigger = null;
		this.setPos = null;
		this.removePos = pos;
	}
	,hasEvent: function() {
		return this._trigger != null;
	}
	,posStr: function(p) {
		return p.fileName + ":" + p.lineNumber;
	}
	,__class__: SingleEventHandler
};
var Slambda = function() { };
Slambda.__name__ = ["Slambda"];
var Slambda1 = function() { };
Slambda1.__name__ = ["Slambda1"];
var Slambda2 = function() { };
Slambda2.__name__ = ["Slambda2"];
var Slambda3 = function() { };
Slambda3.__name__ = ["Slambda3"];
var Slambda4 = function() { };
Slambda4.__name__ = ["Slambda4"];
var Std = function() { };
Std.__name__ = ["Std"];
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
Std.parseInt = function(x) {
	var v = parseInt(x,10);
	if(v == 0 && (HxOverrides.cca(x,1) == 120 || HxOverrides.cca(x,1) == 88)) {
		v = parseInt(x);
	}
	if(isNaN(v)) {
		return null;
	}
	return v;
};
var StringTools = function() { };
StringTools.__name__ = ["StringTools"];
StringTools.isSpace = function(s,pos) {
	var c = HxOverrides.cca(s,pos);
	if(!(c > 8 && c < 14)) {
		return c == 32;
	} else {
		return true;
	}
};
StringTools.ltrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,r)) ++r;
	if(r > 0) {
		return HxOverrides.substr(s,r,l - r);
	} else {
		return s;
	}
};
StringTools.rtrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,l - r - 1)) ++r;
	if(r > 0) {
		return HxOverrides.substr(s,0,l - r);
	} else {
		return s;
	}
};
StringTools.trim = function(s) {
	return StringTools.ltrim(StringTools.rtrim(s));
};
StringTools.lpad = function(s,c,l) {
	if(c.length <= 0) {
		return s;
	}
	while(s.length < l) s = c + s;
	return s;
};
StringTools.rpad = function(s,c,l) {
	if(c.length <= 0) {
		return s;
	}
	while(s.length < l) s += c;
	return s;
};
var Type = function() { };
Type.__name__ = ["Type"];
Type.getClassName = function(c) {
	var a = c.__name__;
	if(a == null) {
		return null;
	}
	return a.join(".");
};
Type.enumEq = function(a,b) {
	if(a == b) {
		return true;
	}
	try {
		if(a[0] != b[0]) {
			return false;
		}
		var _g1 = 2;
		var _g = a.length;
		while(_g1 < _g) {
			var i = _g1++;
			if(!Type.enumEq(a[i],b[i])) {
				return false;
			}
		}
		var e = a.__enum__;
		if(e != b.__enum__ || e == null) {
			return false;
		}
	} catch( e1 ) {
		return false;
	}
	return true;
};
var haxe_StackItem = { __ename__ : true, __constructs__ : ["CFunction","Module","FilePos","Method","LocalFunction"] };
haxe_StackItem.CFunction = ["CFunction",0];
haxe_StackItem.CFunction.__enum__ = haxe_StackItem;
haxe_StackItem.Module = function(m) { var $x = ["Module",1,m]; $x.__enum__ = haxe_StackItem; return $x; };
haxe_StackItem.FilePos = function(s,file,line) { var $x = ["FilePos",2,s,file,line]; $x.__enum__ = haxe_StackItem; return $x; };
haxe_StackItem.Method = function(classname,method) { var $x = ["Method",3,classname,method]; $x.__enum__ = haxe_StackItem; return $x; };
haxe_StackItem.LocalFunction = function(v) { var $x = ["LocalFunction",4,v]; $x.__enum__ = haxe_StackItem; return $x; };
var haxe_CallStack = function() { };
haxe_CallStack.__name__ = ["haxe","CallStack"];
haxe_CallStack.getStack = function(e) {
	if(e == null) {
		return [];
	}
	var oldValue = Error.prepareStackTrace;
	Error.prepareStackTrace = function(error,callsites) {
		var stack = [];
		var _g = 0;
		while(_g < callsites.length) {
			var site = callsites[_g];
			++_g;
			if(haxe_CallStack.wrapCallSite != null) {
				site = haxe_CallStack.wrapCallSite(site);
			}
			var method = null;
			var fullName = site.getFunctionName();
			if(fullName != null) {
				var idx = fullName.lastIndexOf(".");
				if(idx >= 0) {
					var className = HxOverrides.substr(fullName,0,idx);
					var methodName = HxOverrides.substr(fullName,idx + 1,null);
					method = haxe_StackItem.Method(className,methodName);
				}
			}
			stack.push(haxe_StackItem.FilePos(method,site.getFileName(),site.getLineNumber()));
		}
		return stack;
	};
	var a = haxe_CallStack.makeStack(e.stack);
	Error.prepareStackTrace = oldValue;
	return a;
};
haxe_CallStack.callStack = function() {
	try {
		throw new Error();
	} catch( e ) {
		if (e instanceof js__$Boot_HaxeError) e = e.val;
		var a = haxe_CallStack.getStack(e);
		a.shift();
		return a;
	}
};
haxe_CallStack.makeStack = function(s) {
	if(s == null) {
		return [];
	} else if(typeof(s) == "string") {
		var stack = s.split("\n");
		if(stack[0] == "Error") {
			stack.shift();
		}
		var m = [];
		var rie10 = new EReg("^   at ([A-Za-z0-9_. ]+) \\(([^)]+):([0-9]+):([0-9]+)\\)$","");
		var _g = 0;
		while(_g < stack.length) {
			var line = stack[_g];
			++_g;
			if(rie10.match(line)) {
				var path = rie10.matched(1).split(".");
				var meth = path.pop();
				var file = rie10.matched(2);
				var line1 = Std.parseInt(rie10.matched(3));
				m.push(haxe_StackItem.FilePos(meth == "Anonymous function" ? haxe_StackItem.LocalFunction() : meth == "Global code" ? null : haxe_StackItem.Method(path.join("."),meth),file,line1));
			} else {
				m.push(haxe_StackItem.Module(StringTools.trim(line)));
			}
		}
		return m;
	} else {
		return s;
	}
};
var haxe_IMap = function() { };
haxe_IMap.__name__ = ["haxe","IMap"];
haxe_IMap.prototype = {
	__class__: haxe_IMap
};
var haxe_Timer = function(time_ms) {
	var me = this;
	this.id = setInterval(function() {
		me.run();
	},time_ms);
};
haxe_Timer.__name__ = ["haxe","Timer"];
haxe_Timer.delay = function(f,time_ms) {
	var t = new haxe_Timer(time_ms);
	t.run = function() {
		t.stop();
		f();
	};
	return t;
};
haxe_Timer.prototype = {
	stop: function() {
		if(this.id == null) {
			return;
		}
		clearInterval(this.id);
		this.id = null;
	}
	,run: function() {
	}
	,__class__: haxe_Timer
};
var haxe_ds_Option = { __ename__ : true, __constructs__ : ["Some","None"] };
haxe_ds_Option.Some = function(v) { var $x = ["Some",0,v]; $x.__enum__ = haxe_ds_Option; return $x; };
haxe_ds_Option.None = ["None",1];
haxe_ds_Option.None.__enum__ = haxe_ds_Option;
var haxe_ds_StringMap = function() {
	this.h = { };
};
haxe_ds_StringMap.__name__ = ["haxe","ds","StringMap"];
haxe_ds_StringMap.__interfaces__ = [haxe_IMap];
haxe_ds_StringMap.prototype = {
	get: function(key) {
		if(__map_reserved[key] != null) {
			return this.getReserved(key);
		}
		return this.h[key];
	}
	,setReserved: function(key,value) {
		if(this.rh == null) {
			this.rh = { };
		}
		this.rh["$" + key] = value;
	}
	,getReserved: function(key) {
		if(this.rh == null) {
			return null;
		} else {
			return this.rh["$" + key];
		}
	}
	,existsReserved: function(key) {
		if(this.rh == null) {
			return false;
		}
		return this.rh.hasOwnProperty("$" + key);
	}
	,keys: function() {
		return HxOverrides.iter(this.arrayKeys());
	}
	,arrayKeys: function() {
		var out = [];
		for( var key in this.h ) {
		if(this.h.hasOwnProperty(key)) {
			out.push(key);
		}
		}
		if(this.rh != null) {
			for( var key in this.rh ) {
			if(key.charCodeAt(0) == 36) {
				out.push(key.substr(1));
			}
			}
		}
		return out;
	}
	,__class__: haxe_ds_StringMap
};
var haxecontracts_Contract = function() { };
haxecontracts_Contract.__name__ = ["haxecontracts","Contract"];
haxecontracts_Contract.requires = function(condition,message) {
	if(message == null) {
		message = "Contract precondition failed.";
	}
	throw new js__$Boot_HaxeError(haxecontracts_Contract.implementationError);
};
haxecontracts_Contract.ensures = function(condition,message) {
	if(message == null) {
		message = "Contract postcondition failed.";
	}
	throw new js__$Boot_HaxeError(haxecontracts_Contract.implementationError);
};
haxecontracts_Contract.invariant = function(condition,message) {
	if(message == null) {
		message = "Contract invariant failed.";
	}
	throw new js__$Boot_HaxeError(haxecontracts_Contract.implementationError);
};
haxecontracts_Contract.get_result = function() {
	throw new js__$Boot_HaxeError(haxecontracts_Contract.implementationError);
};
haxecontracts_Contract.old = function(methodParameter) {
	throw new js__$Boot_HaxeError("Contract.old can only be called within Contract.ensures");
};
var haxecontracts_ContractException = function(message,object,$arguments,innerException,p) {
	if(message == null) {
		message = "";
	}
	this.message = message;
	this.object = object;
	this["arguments"] = $arguments == null ? [] : $arguments;
	this.pos = p;
	this.callStack = [];
	this.innerException = innerException;
	var _g = 0;
	var _g1 = haxe_CallStack.callStack();
	while(_g < _g1.length) {
		var s = _g1[_g];
		++_g;
		if(s[1] == 2) {
			var file = s[3];
			if(file != "haxecontracts/ContractException.hx") {
				this.callStack.push(s);
			}
		}
	}
};
haxecontracts_ContractException.__name__ = ["haxecontracts","ContractException"];
haxecontracts_ContractException.prototype = {
	toString: function() {
		var innerEx = this.innerException == null ? "" : ": " + Std.string(this.innerException);
		return this.message + (" (" + this.pos.fileName + ":" + this.pos.lineNumber + innerEx + ") ") + Std.string(this["arguments"]) + (this.object != null ? " " + Std.string(this.object) : "");
	}
	,__class__: haxecontracts_ContractException
};
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	this.message = String(val);
	if(Error.captureStackTrace) {
		Error.captureStackTrace(this,js__$Boot_HaxeError);
	}
};
js__$Boot_HaxeError.__name__ = ["js","_Boot","HaxeError"];
js__$Boot_HaxeError.wrap = function(val) {
	if((val instanceof Error)) {
		return val;
	} else {
		return new js__$Boot_HaxeError(val);
	}
};
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
	__class__: js__$Boot_HaxeError
});
var js_Boot = function() { };
js_Boot.__name__ = ["js","Boot"];
js_Boot.getClass = function(o) {
	if((o instanceof Array) && o.__enum__ == null) {
		return Array;
	} else {
		var cl = o.__class__;
		if(cl != null) {
			return cl;
		}
		var name = js_Boot.__nativeClassName(o);
		if(name != null) {
			return js_Boot.__resolveNativeClass(name);
		}
		return null;
	}
};
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o instanceof Array) {
			if(o.__enum__) {
				if(o.length == 2) {
					return o[0];
				}
				var str = o[0] + "(";
				s += "\t";
				var _g1 = 2;
				var _g = o.length;
				while(_g1 < _g) {
					var i = _g1++;
					if(i != 2) {
						str += "," + js_Boot.__string_rec(o[i],s);
					} else {
						str += js_Boot.__string_rec(o[i],s);
					}
				}
				return str + ")";
			}
			var l = o.length;
			var i1;
			var str1 = "[";
			s += "\t";
			var _g11 = 0;
			var _g2 = l;
			while(_g11 < _g2) {
				var i2 = _g11++;
				str1 += (i2 > 0 ? "," : "") + js_Boot.__string_rec(o[i2],s);
			}
			str1 += "]";
			return str1;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var k = null;
		var str2 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str2.length != 2) {
			str2 += ", \n";
		}
		str2 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str2 += "\n" + s + "}";
		return str2;
	case "string":
		return o;
	default:
		return String(o);
	}
};
js_Boot.__interfLoop = function(cc,cl) {
	if(cc == null) {
		return false;
	}
	if(cc == cl) {
		return true;
	}
	var intf = cc.__interfaces__;
	if(intf != null) {
		var _g1 = 0;
		var _g = intf.length;
		while(_g1 < _g) {
			var i = _g1++;
			var i1 = intf[i];
			if(i1 == cl || js_Boot.__interfLoop(i1,cl)) {
				return true;
			}
		}
	}
	return js_Boot.__interfLoop(cc.__super__,cl);
};
js_Boot.__instanceof = function(o,cl) {
	if(cl == null) {
		return false;
	}
	switch(cl) {
	case Array:
		if((o instanceof Array)) {
			return o.__enum__ == null;
		} else {
			return false;
		}
		break;
	case Bool:
		return typeof(o) == "boolean";
	case Dynamic:
		return true;
	case Float:
		return typeof(o) == "number";
	case Int:
		if(typeof(o) == "number") {
			return (o|0) === o;
		} else {
			return false;
		}
		break;
	case String:
		return typeof(o) == "string";
	default:
		if(o != null) {
			if(typeof(cl) == "function") {
				if(o instanceof cl) {
					return true;
				}
				if(js_Boot.__interfLoop(js_Boot.getClass(o),cl)) {
					return true;
				}
			} else if(typeof(cl) == "object" && js_Boot.__isNativeObj(cl)) {
				if(o instanceof cl) {
					return true;
				}
			}
		} else {
			return false;
		}
		if(cl == Class ? o.__name__ != null : false) {
			return true;
		}
		if(cl == Enum ? o.__ename__ != null : false) {
			return true;
		}
		return o.__enum__ == cl;
	}
};
js_Boot.__cast = function(o,t) {
	if(js_Boot.__instanceof(o,t)) {
		return o;
	} else {
		throw new js__$Boot_HaxeError("Cannot cast " + Std.string(o) + " to " + Std.string(t));
	}
};
js_Boot.__nativeClassName = function(o) {
	var name = js_Boot.__toStr.call(o).slice(8,-1);
	if(name == "Object" || name == "Function" || name == "Math" || name == "JSON") {
		return null;
	}
	return name;
};
js_Boot.__isNativeObj = function(o) {
	return js_Boot.__nativeClassName(o) != null;
};
js_Boot.__resolveNativeClass = function(name) {
	return $global[name];
};
var views_MainView = function(bookshelf,cardReader,workspace,itemScanner,screenView,printer) {
	this.bookshelf = bookshelf;
	this.workspace = workspace;
	this.cardReader = cardReader;
	this.itemScanner = itemScanner;
	this.screenView = screenView;
	this.printer = printer;
};
views_MainView.__name__ = ["views","MainView"];
views_MainView.__interfaces__ = [mithril_Mithril];
views_MainView.prototype = {
	mount: function() {
		m.mount(_$HtmlElements_HtmlElements_$Impl_$.toElement("screen"),this.screenView);
		var f = $bind(this,this.surfaceView);
		var a1 = this.bookshelf;
		var tmp = function() {
			return f(a1);
		};
		m.mount(_$HtmlElements_HtmlElements_$Impl_$.toElement("bookshelf"),{ view : tmp});
		var f1 = $bind(this,this.surfaceView);
		var a11 = this.cardReader;
		var tmp1 = function() {
			return f1(a11);
		};
		m.mount(_$HtmlElements_HtmlElements_$Impl_$.toElement("card-reader"),{ view : tmp1});
		var f2 = $bind(this,this.surfaceView);
		var a12 = this.itemScanner;
		var tmp2 = function() {
			return f2(a12);
		};
		m.mount(_$HtmlElements_HtmlElements_$Impl_$.toElement("scanner"),{ view : tmp2});
		var f3 = $bind(this,this.surfaceView);
		var a13 = this.workspace;
		var tmp3 = function() {
			return f3(a13);
		};
		m.mount(_$HtmlElements_HtmlElements_$Impl_$.toElement("workspace"),{ view : tmp3});
		m.mount(_$HtmlElements_HtmlElements_$Impl_$.toElement("printer"),this.printer);
	}
	,surfaceView: function(surface) {
		return surface.map(function(item) {
			var _g = item == null ? null : js_Boot.getClass(item);
			if(_g == null) {
				var unknown = _g;
				var tmp = "View not found for: " + Type.getClassName(unknown);
				return m.m("div",{ style : "color:red"},tmp);
			} else {
				switch(_g) {
				case Bluray:
					var item1 = item;
					return m.m(".bluray.cover",item1.title);
				case Book:
					var item2 = item;
					return m.m(".book.cover",item2.title);
				case Card:
					return m.m("img#card[src=images/card.svg]");
				default:
					var unknown1 = _g;
					var tmp1 = "View not found for: " + Type.getClassName(unknown1);
					return m.m("div",{ style : "color:red"},tmp1);
				}
			}
		});
	}
	,__class__: views_MainView
};
var views_ScreenState = { __ename__ : true, __constructs__ : ["Welcome","EnterPin","DisplayBorrowedItems","ThankYou","TooManyInvalidPin","RemoveCard","InvalidCard","InvalidLoanItem","ItemAlreadyBorrowed","DontForgetLibraryCard"] };
views_ScreenState.Welcome = ["Welcome",0];
views_ScreenState.Welcome.__enum__ = views_ScreenState;
views_ScreenState.EnterPin = function(data) { var $x = ["EnterPin",1,data]; $x.__enum__ = views_ScreenState; return $x; };
views_ScreenState.DisplayBorrowedItems = function(scannedItems) { var $x = ["DisplayBorrowedItems",2,scannedItems]; $x.__enum__ = views_ScreenState; return $x; };
views_ScreenState.ThankYou = ["ThankYou",3];
views_ScreenState.ThankYou.__enum__ = views_ScreenState;
views_ScreenState.TooManyInvalidPin = ["TooManyInvalidPin",4];
views_ScreenState.TooManyInvalidPin.__enum__ = views_ScreenState;
views_ScreenState.RemoveCard = ["RemoveCard",5];
views_ScreenState.RemoveCard.__enum__ = views_ScreenState;
views_ScreenState.InvalidCard = ["InvalidCard",6];
views_ScreenState.InvalidCard.__enum__ = views_ScreenState;
views_ScreenState.InvalidLoanItem = ["InvalidLoanItem",7];
views_ScreenState.InvalidLoanItem.__enum__ = views_ScreenState;
views_ScreenState.ItemAlreadyBorrowed = ["ItemAlreadyBorrowed",8];
views_ScreenState.ItemAlreadyBorrowed.__enum__ = views_ScreenState;
views_ScreenState.DontForgetLibraryCard = ["DontForgetLibraryCard",9];
views_ScreenState.DontForgetLibraryCard.__enum__ = views_ScreenState;
var views_ScreenView = function(initialState) {
	this._onFinishWithReceiptClicked = new SingleEventHandler();
	this._onFinishWithoutReceiptClicked = new SingleEventHandler();
	this._onPinCodeEntered = new SingleEventHandler();
	this.pinBuffer = "";
	this.display(initialState);
};
views_ScreenView.__name__ = ["views","ScreenView"];
views_ScreenView.__interfaces__ = [mithril_Mithril,haxecontracts_HaxeContracts];
views_ScreenView.prototype = {
	display: function(state) {
		try {
			if(state == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [state != null]",this,[state],null,{ fileName : "ScreenView.hx", lineNumber : 34, className : "views.ScreenView", methodName : "display"}));
			}
		} catch( e ) {
			if (e instanceof js__$Boot_HaxeError) e = e.val;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [state != null]",this,[state],e,{ fileName : "ScreenView.hx", lineNumber : 34, className : "views.ScreenView", methodName : "display"}));
		}
		if(this.messageTimer != null) {
			this.messageTimer.stop();
		}
		this.currentState = state;
		m.redraw();
	}
	,displayMessage: function(state,waitMs,thenDisplay) {
		if(thenDisplay == null) {
			thenDisplay = this.currentState;
		}
		this.display(state);
		this.messageTimer = new haxe_Timer(waitMs);
		var f = $bind(this,this.display);
		var a1 = thenDisplay;
		var tmp = function() {
			f(a1);
		};
		this.messageTimer.run = tmp;
	}
	,onPinCodeEntered: function(callback,pos) {
		this._onPinCodeEntered.set(callback,pos);
	}
	,onFinishWithoutReceiptClicked: function(callback,pos) {
		this._onFinishWithoutReceiptClicked.set(callback,pos);
	}
	,onFinishWithReceiptClicked: function(callback,pos) {
		this._onFinishWithReceiptClicked.set(callback,pos);
	}
	,view: function() {
		if(arguments.length > 0 && arguments[0].tag != this) return arguments[0].tag.view.apply(arguments[0].tag, arguments);
		var _g = this.currentState;
		switch(_g[1]) {
		case 0:
			return this.welcome();
		case 1:
			var data = _g[2];
			return this.enterPin(data.previousAttemptFailed);
		case 2:
			var scannedItems = _g[2];
			return this.displayBorrowedItems(scannedItems);
		case 3:
			return this.thankYou();
		case 4:
			return this.tooManyInvalidPin();
		case 6:
			return this.invalidCard();
		case 7:
			return this.invalidLoanItem();
		case 8:
			return this.itemAlreadyBorrowed();
		case 9:
			return this.dontForgetLibraryCard();
		default:
			return m.m(".content.red","View not found: " + Std.string(this.currentState));
		}
	}
	,welcome: function() {
		return m.m(".content",[m.m("p","Welcome to the library borrowing machine!"),m.m("p",m.m("strong","Please insert your card into the reader."))]);
	}
	,enterPin: function(previousAttemptFailed) {
		var _gthis = this;
		return [m.m(".content",previousAttemptFailed ? m.m(".red","Incorrect PIN. Enter your 4-digit PIN.") : m.m("p","Enter your 4-digit PIN.")),m.m(".content",m.m("p",this.pinBuffer.length == 0 ? m.trust("&nbsp;") : StringTools.rpad("","*",this.pinBuffer.length))),m.m(".content.keypad",["1","2","3","4","5","6","7","8","9","0"].map(function(key) {
			var f = $bind(_gthis,_gthis.enterPinKeyPressed);
			var a1 = key;
			return m.m(".key",{ onclick : function() {
				f(a1);
			}},key);
		}))];
	}
	,enterPinKeyPressed: function(key) {
		this.pinBuffer += key;
		if(this.pinBuffer.length < 4) {
			return;
		}
		var pin = this.pinBuffer;
		this.pinBuffer = "";
		if(this._onPinCodeEntered.hasEvent()) {
			(this._onPinCodeEntered.get_trigger())(pin);
		}
	}
	,tooManyInvalidPin: function() {
		return m.m(".content",[m.m(".red","Incorrect PIN too many times."),m.m("p","Please remove your card before trying again.")]);
	}
	,displayBorrowedItems: function(scannedItems) {
		var _gthis = this;
		var tmp = m.m("p","Scan the items you want to borrow on the dark red area.");
		var tmp1 = m.m("p",[m.m("button.-success",{ style : "margin-right:2px", onclick : function() {
			if(_gthis._onFinishWithReceiptClicked.hasEvent()) {
				(_gthis._onFinishWithReceiptClicked.get_trigger())();
			}
		}},"Finish with receipt"),m.m("button.-success",{ onclick : function() {
			if(_gthis._onFinishWithoutReceiptClicked.hasEvent()) {
				(_gthis._onFinishWithoutReceiptClicked.get_trigger())();
			}
		}},"Finish without receipt")]);
		var tmp2 = m.m("thead",m.m("tr",[m.m("th","Title"),m.m("th","Return date")]));
		var _g7 = [];
		var scanned = $iterator(scannedItems)();
		while(scanned.hasNext()) {
			var scanned1 = scanned.next();
			_g7.push(m.m("tr",[m.m("td",scanned1.item.title),m.m("td",DateTools.format(scanned1.returnDate,"%Y-%m-%d"))]));
		}
		return m.m(".content",[tmp,tmp1,m.m("table",[tmp2,m.m("tbody",_g7)])]);
	}
	,invalidCard: function() {
		return m.m(".content",[m.m(".red","Library card not valid."),m.m("p","Please contact support.")]);
	}
	,thankYou: function() {
		return m.m(".content",[m.m("p","Thank you for using the automatic borrowing service!")]);
	}
	,dontForgetLibraryCard: function() {
		return m.m(".content",[m.m("p",m.m("strong","Don't forget your library card!"))]);
	}
	,invalidLoanItem: function() {
		return m.m(".content",[m.m(".red","Loan item not valid."),m.m("p","Please contact support.")]);
	}
	,itemAlreadyBorrowed: function() {
		return m.m(".content",[m.m(".red","Loan item already borrowed."),m.m("p","Please contact support.")]);
	}
	,__class__: views_ScreenView
};
function $iterator(o) { if( o instanceof Array ) return function() { return HxOverrides.iter(o); }; return typeof(o.iterator) == 'function' ? $bind(o,o.iterator) : o.iterator; }
var $_, $fid = 0;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $fid++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = function(){ return f.method.apply(f.scope, arguments); }; f.scope = o; f.method = m; o.hx__closures__[m.__id__] = f; } return f; }
String.prototype.__class__ = String;
String.__name__ = ["String"];
Array.__name__ = ["Array"];
Date.prototype.__class__ = Date;
Date.__name__ = ["Date"];
var Int = { __name__ : ["Int"]};
var Dynamic = { __name__ : ["Dynamic"]};
var Float = Number;
Float.__name__ = ["Float"];
var Bool = Boolean;
Bool.__ename__ = ["Bool"];
var Class = { __name__ : ["Class"]};
var Enum = { };
var __map_reserved = {}
try {
var __varName = window.m;
(function(m) {
			if (m.m) return;
			m.m = function() {
				try { 
					for(var i=0; i < arguments.length; ++i) if(arguments[i] instanceof List) {
						var list = arguments[i].h; arguments[i] = [];
						while(list != null) { arguments[i].push(l[0]); list = l[1]; }
					}
				} catch(e) {}
				return m.apply(this, arguments);
			}
		})(__varName);
} catch(_) {}
try {
GLOBAL.m = require("mithril");
var __varName1 = GLOBAL.m;
(function(m) {
			if (m.m) return;
			m.m = function() {
				try { 
					for(var i=0; i < arguments.length; ++i) if(arguments[i] instanceof List) {
						var list = arguments[i].h; arguments[i] = [];
						while(list != null) { arguments[i].push(l[0]); list = l[1]; }
					}
				} catch(e) {}
				return m.apply(this, arguments);
			}
		})(__varName1);
} catch(_) {}
BorrowLibraryItems.__meta__ = { fields : { cardReader : { role : null}, scanner : { role : null}, scannedItems : { role : null}, screen : { role : null}, finishButtons : { role : null}, keypad : { role : null}, printer : { role : null}, library : { role : null}}};
BorrowLibraryItems.maxPinAttempts = 3;
BorrowLoanItem.__meta__ = { fields : { listOfLoans : { role : null}, listOfLibraryCards : { role : null}, listOfItems : { role : null}, loanItem : { role : null}, borrower : { role : null}}};
Book.__meta__ = { obj : { dataClassRtti : [{ rfid : "String", title : "String", loanTimeDays : "Int"}]}};
Bluray.__meta__ = { obj : { dataClassRtti : [{ rfid : "String", title : "String", length : "Int", loanTimeDays : "Int"}]}};
Card.__meta__ = { obj : { dataClassRtti : [{ rfid : "String", name : "String", pin : "String"}]}};
LibraryLoan.__meta__ = { obj : { dataClassRtti : [{ loanItemRfid : "String", borrowerRfid : "String", created : "Date", returnDate : "Date"}]}};
DateTools.DAY_SHORT_NAMES = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
DateTools.DAY_NAMES = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
DateTools.MONTH_SHORT_NAMES = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
DateTools.MONTH_NAMES = ["January","February","March","April","May","June","July","August","September","October","November","December"];
_$HtmlElements_HtmlElements_$Impl_$.Bookshelf = "bookshelf";
_$HtmlElements_HtmlElements_$Impl_$.Printer = "printer";
_$HtmlElements_HtmlElements_$Impl_$.Screen = "screen";
_$HtmlElements_HtmlElements_$Impl_$.CardReader = "card-reader";
_$HtmlElements_HtmlElements_$Impl_$.Workspace = "workspace";
_$HtmlElements_HtmlElements_$Impl_$.Scanner = "scanner";
_$HtmlElements_HtmlElements_$Impl_$.Card = "card";
haxecontracts_Contract.implementationError = "A class calling haxecontracts.Contract must implement haxecontracts.HaxeContracts";
js_Boot.__toStr = ({ }).toString;
Main.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);

//# sourceMappingURL=haxedci-example.js.map