// Generated by Haxe 4.0.5
(function ($global) { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); },$hxEnums = $hxEnums || {},$_;
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var Data = function() { };
Data.__name__ = "Data";
var RfidItem = function() { };
RfidItem.__name__ = "RfidItem";
RfidItem.__isInterface__ = true;
RfidItem.prototype = {
	__class__: RfidItem
};
var LoanItem = function() { };
LoanItem.__name__ = "LoanItem";
LoanItem.__isInterface__ = true;
LoanItem.__interfaces__ = [RfidItem];
LoanItem.prototype = {
	__class__: LoanItem
};
var ScannedItem = function() { };
ScannedItem.__name__ = "ScannedItem";
ScannedItem.__isInterface__ = true;
ScannedItem.prototype = {
	__class__: ScannedItem
};
var contexts_DragDropItem = function() { };
contexts_DragDropItem.__name__ = "contexts.DragDropItem";
contexts_DragDropItem.__isInterface__ = true;
var DataClass = function() { };
DataClass.__name__ = "DataClass";
DataClass.__isInterface__ = true;
var haxecontracts_HaxeContracts = function() { };
haxecontracts_HaxeContracts.__name__ = "haxecontracts.HaxeContracts";
haxecontracts_HaxeContracts.__isInterface__ = true;
var Book = function(data) {
	var _g = Book.validate(data);
	switch(_g._hx_index) {
	case 0:
		var errors = _g.v;
		throw new js__$Boot_HaxeError(new dataclass_DataClassException(this,data,errors));
	case 1:
		break;
	}
	if(data.rfid != null) {
		this.rfid = data.rfid;
	}
	if(data.title != null) {
		this.title = data.title;
	}
	if(data.loanTimeDays != null) {
		this.loanTimeDays = data.loanTimeDays;
	}
};
Book.__name__ = "Book";
Book.__interfaces__ = [LoanItem,contexts_DragDropItem,DataClass,haxecontracts_HaxeContracts];
Book.validate = function(data) {
	var errors = null;
	var hasErrors = false;
	var setError = function(field,value) {
		if(errors == null) {
			errors = new haxe_ds_StringMap();
		}
		if(__map_reserved[field] != null) {
			errors.setReserved(field,value);
		} else {
			errors.h[field] = value;
		}
		hasErrors = true;
	};
	if(data.rfid == null) {
		setError("rfid",haxe_ds_Option.None);
	} else {
		var v = data.rfid;
		if(v.length <= 0) {
			setError("rfid",haxe_ds_Option.Some(v));
		}
	}
	if(data.title == null) {
		setError("title",haxe_ds_Option.None);
	} else {
		var v1 = data.title;
		if(v1.length <= 0) {
			setError("title",haxe_ds_Option.Some(v1));
		}
	}
	if(data.loanTimeDays == null) {
		setError("loanTimeDays",haxe_ds_Option.None);
	} else {
		var v2 = data.loanTimeDays;
		if(v2 <= 0) {
			setError("loanTimeDays",haxe_ds_Option.Some(v2));
		}
	}
	if(hasErrors) {
		return haxe_ds_Option.Some(errors);
	} else {
		return haxe_ds_Option.None;
	}
};
Book.copy = function(dataClass,update) {
	if(update == null) {
		update = { };
	}
	if(!Object.prototype.hasOwnProperty.call(update,"rfid")) {
		update.rfid = dataClass.rfid;
	}
	if(!Object.prototype.hasOwnProperty.call(update,"title")) {
		update.title = dataClass.title;
	}
	if(!Object.prototype.hasOwnProperty.call(update,"loanTimeDays")) {
		update.loanTimeDays = dataClass.loanTimeDays;
	}
	return new Book(update);
};
Book.prototype = {
	__class__: Book
};
var Bluray = function(data) {
	var _g = Bluray.validate(data);
	switch(_g._hx_index) {
	case 0:
		var errors = _g.v;
		throw new js__$Boot_HaxeError(new dataclass_DataClassException(this,data,errors));
	case 1:
		break;
	}
	if(data.rfid != null) {
		this.rfid = data.rfid;
	}
	if(data.title != null) {
		this.title = data.title;
	}
	if(data.length != null) {
		this.length = data.length;
	}
	if(data.loanTimeDays != null) {
		this.loanTimeDays = data.loanTimeDays;
	}
};
Bluray.__name__ = "Bluray";
Bluray.__interfaces__ = [LoanItem,contexts_DragDropItem,DataClass,haxecontracts_HaxeContracts];
Bluray.validate = function(data) {
	var errors = null;
	var hasErrors = false;
	var setError = function(field,value) {
		if(errors == null) {
			errors = new haxe_ds_StringMap();
		}
		if(__map_reserved[field] != null) {
			errors.setReserved(field,value);
		} else {
			errors.h[field] = value;
		}
		hasErrors = true;
	};
	if(data.rfid == null) {
		setError("rfid",haxe_ds_Option.None);
	} else {
		var v = data.rfid;
		if(v.length <= 0) {
			setError("rfid",haxe_ds_Option.Some(v));
		}
	}
	if(data.title == null) {
		setError("title",haxe_ds_Option.None);
	} else {
		var v1 = data.title;
		if(v1.length <= 0) {
			setError("title",haxe_ds_Option.Some(v1));
		}
	}
	if(data.length == null) {
		setError("length",haxe_ds_Option.None);
	} else {
		var v2 = data.length;
		if(v2 <= 0) {
			setError("length",haxe_ds_Option.Some(v2));
		}
	}
	if(data.loanTimeDays == null) {
		setError("loanTimeDays",haxe_ds_Option.None);
	} else {
		var v3 = data.loanTimeDays;
		if(v3 <= 0) {
			setError("loanTimeDays",haxe_ds_Option.Some(v3));
		}
	}
	if(hasErrors) {
		return haxe_ds_Option.Some(errors);
	} else {
		return haxe_ds_Option.None;
	}
};
Bluray.copy = function(dataClass,update) {
	if(update == null) {
		update = { };
	}
	if(!Object.prototype.hasOwnProperty.call(update,"rfid")) {
		update.rfid = dataClass.rfid;
	}
	if(!Object.prototype.hasOwnProperty.call(update,"title")) {
		update.title = dataClass.title;
	}
	if(!Object.prototype.hasOwnProperty.call(update,"length")) {
		update.length = dataClass.length;
	}
	if(!Object.prototype.hasOwnProperty.call(update,"loanTimeDays")) {
		update.loanTimeDays = dataClass.loanTimeDays;
	}
	return new Bluray(update);
};
Bluray.prototype = {
	__class__: Bluray
};
var LibraryCard = function(data) {
	var _g = LibraryCard.validate(data);
	switch(_g._hx_index) {
	case 0:
		var errors = _g.v;
		throw new js__$Boot_HaxeError(new dataclass_DataClassException(this,data,errors));
	case 1:
		break;
	}
	if(data.rfid != null) {
		this.rfid = data.rfid;
	}
	if(data.name != null) {
		this.name = data.name;
	}
	if(data.pin != null) {
		this.pin = data.pin;
	}
};
LibraryCard.__name__ = "LibraryCard";
LibraryCard.__interfaces__ = [RfidItem,contexts_DragDropItem,DataClass,haxecontracts_HaxeContracts];
LibraryCard.validate = function(data) {
	var errors = null;
	var hasErrors = false;
	var setError = function(field,value) {
		if(errors == null) {
			errors = new haxe_ds_StringMap();
		}
		if(__map_reserved[field] != null) {
			errors.setReserved(field,value);
		} else {
			errors.h[field] = value;
		}
		hasErrors = true;
	};
	if(data.rfid == null) {
		setError("rfid",haxe_ds_Option.None);
	} else {
		var v = data.rfid;
		if(v.length <= 0) {
			setError("rfid",haxe_ds_Option.Some(v));
		}
	}
	if(data.name == null) {
		setError("name",haxe_ds_Option.None);
	} else {
		var v1 = data.name;
		if(v1.length <= 0) {
			setError("name",haxe_ds_Option.Some(v1));
		}
	}
	if(data.pin == null) {
		setError("pin",haxe_ds_Option.None);
	} else {
		var v2 = data.pin;
		if(!new EReg("^\\d{4}$","").match(v2 == null ? "null" : "" + v2)) {
			setError("pin",haxe_ds_Option.Some(v2));
		}
	}
	if(hasErrors) {
		return haxe_ds_Option.Some(errors);
	} else {
		return haxe_ds_Option.None;
	}
};
LibraryCard.copy = function(dataClass,update) {
	if(update == null) {
		update = { };
	}
	if(!Object.prototype.hasOwnProperty.call(update,"rfid")) {
		update.rfid = dataClass.rfid;
	}
	if(!Object.prototype.hasOwnProperty.call(update,"name")) {
		update.name = dataClass.name;
	}
	if(!Object.prototype.hasOwnProperty.call(update,"pin")) {
		update.pin = dataClass.pin;
	}
	return new LibraryCard(update);
};
LibraryCard.prototype = {
	__class__: LibraryCard
};
var LibraryLoan = function(data) {
	var _g = LibraryLoan.validate(data);
	switch(_g._hx_index) {
	case 0:
		var errors = _g.v;
		throw new js__$Boot_HaxeError(new dataclass_DataClassException(this,data,errors));
	case 1:
		break;
	}
	if(data.loanItemRfid != null) {
		this.loanItemRfid = data.loanItemRfid;
	}
	if(data.borrowerRfid != null) {
		this.borrowerRfid = data.borrowerRfid;
	}
	if(data.created != null) {
		this.created = data.created;
	}
	if(data.returnDate != null) {
		this.returnDate = data.returnDate;
	}
};
LibraryLoan.__name__ = "LibraryLoan";
LibraryLoan.__interfaces__ = [DataClass,haxecontracts_HaxeContracts];
LibraryLoan.validate = function(data) {
	var errors = null;
	var hasErrors = false;
	var setError = function(field,value) {
		if(errors == null) {
			errors = new haxe_ds_StringMap();
		}
		if(__map_reserved[field] != null) {
			errors.setReserved(field,value);
		} else {
			errors.h[field] = value;
		}
		hasErrors = true;
	};
	if(data.loanItemRfid == null) {
		setError("loanItemRfid",haxe_ds_Option.None);
	} else {
		var v = data.loanItemRfid;
		if(v.length <= 0) {
			setError("loanItemRfid",haxe_ds_Option.Some(v));
		}
	}
	if(data.borrowerRfid == null) {
		setError("borrowerRfid",haxe_ds_Option.None);
	} else {
		var v1 = data.borrowerRfid;
		if(v1.length <= 0) {
			setError("borrowerRfid",haxe_ds_Option.Some(v1));
		}
	}
	if(data.created == null) {
		setError("created",haxe_ds_Option.None);
	}
	if(data.returnDate == null) {
		setError("returnDate",haxe_ds_Option.None);
	}
	if(hasErrors) {
		return haxe_ds_Option.Some(errors);
	} else {
		return haxe_ds_Option.None;
	}
};
LibraryLoan.copy = function(dataClass,update) {
	if(update == null) {
		update = { };
	}
	if(!Object.prototype.hasOwnProperty.call(update,"loanItemRfid")) {
		update.loanItemRfid = dataClass.loanItemRfid;
	}
	if(!Object.prototype.hasOwnProperty.call(update,"borrowerRfid")) {
		update.borrowerRfid = dataClass.borrowerRfid;
	}
	if(!Object.prototype.hasOwnProperty.call(update,"created")) {
		update.created = dataClass.created;
	}
	if(!Object.prototype.hasOwnProperty.call(update,"returnDate")) {
		update.returnDate = dataClass.returnDate;
	}
	return new LibraryLoan(update);
};
LibraryLoan.prototype = {
	__class__: LibraryLoan
};
var ReceiptItem = function(item,returnDate) {
	this.item = item;
	this.returnDate = returnDate;
	try {
		if(this.item == null) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [this.item != null]",this,[item,returnDate],null,{ fileName : "src/Data.hx", lineNumber : 96, className : "ReceiptItem", methodName : "new"}));
		}
	} catch( e ) {
		throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [this.item != null]",this,[item,returnDate],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "src/Data.hx", lineNumber : 96, className : "ReceiptItem", methodName : "new"}));
	}
	try {
		if(this.returnDate == null) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [this.returnDate != null]",this,[item,returnDate],null,{ fileName : "src/Data.hx", lineNumber : 97, className : "ReceiptItem", methodName : "new"}));
		}
	} catch( e1 ) {
		throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [this.returnDate != null]",this,[item,returnDate],((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1,{ fileName : "src/Data.hx", lineNumber : 97, className : "ReceiptItem", methodName : "new"}));
	}
};
ReceiptItem.__name__ = "ReceiptItem";
ReceiptItem.__interfaces__ = [ScannedItem,haxecontracts_HaxeContracts];
ReceiptItem.prototype = {
	__class__: ReceiptItem
};
var DateTools = function() { };
DateTools.__name__ = "DateTools";
DateTools.__format_get = function(d,e) {
	switch(e) {
	case "%":
		return "%";
	case "A":
		return DateTools.DAY_NAMES[d.getDay()];
	case "B":
		return DateTools.MONTH_NAMES[d.getMonth()];
	case "C":
		return StringTools.lpad(Std.string(d.getFullYear() / 100 | 0),"0",2);
	case "D":
		return DateTools.__format(d,"%m/%d/%y");
	case "F":
		return DateTools.__format(d,"%Y-%m-%d");
	case "I":case "l":
		var hour = d.getHours() % 12;
		return StringTools.lpad(Std.string(hour == 0 ? 12 : hour),e == "I" ? "0" : " ",2);
	case "M":
		return StringTools.lpad(Std.string(d.getMinutes()),"0",2);
	case "R":
		return DateTools.__format(d,"%H:%M");
	case "S":
		return StringTools.lpad(Std.string(d.getSeconds()),"0",2);
	case "T":
		return DateTools.__format(d,"%H:%M:%S");
	case "Y":
		return Std.string(d.getFullYear());
	case "a":
		return DateTools.DAY_SHORT_NAMES[d.getDay()];
	case "b":case "h":
		return DateTools.MONTH_SHORT_NAMES[d.getMonth()];
	case "d":
		return StringTools.lpad(Std.string(d.getDate()),"0",2);
	case "e":
		return Std.string(d.getDate());
	case "H":case "k":
		return StringTools.lpad(Std.string(d.getHours()),e == "H" ? "0" : " ",2);
	case "m":
		return StringTools.lpad(Std.string(d.getMonth() + 1),"0",2);
	case "n":
		return "\n";
	case "p":
		if(d.getHours() > 11) {
			return "PM";
		} else {
			return "AM";
		}
		break;
	case "r":
		return DateTools.__format(d,"%I:%M:%S %p");
	case "s":
		return Std.string(d.getTime() / 1000 | 0);
	case "t":
		return "\t";
	case "u":
		var t = d.getDay();
		if(t == 0) {
			return "7";
		} else if(t == null) {
			return "null";
		} else {
			return "" + t;
		}
		break;
	case "w":
		return Std.string(d.getDay());
	case "y":
		return StringTools.lpad(Std.string(d.getFullYear() % 100),"0",2);
	default:
		throw new js__$Boot_HaxeError("Date.format %" + e + "- not implemented yet.");
	}
};
DateTools.__format = function(d,f) {
	var r_b = "";
	var p = 0;
	while(true) {
		var np = f.indexOf("%",p);
		if(np < 0) {
			break;
		}
		var len = np - p;
		r_b += len == null ? HxOverrides.substr(f,p,null) : HxOverrides.substr(f,p,len);
		r_b += Std.string(DateTools.__format_get(d,HxOverrides.substr(f,np + 1,1)));
		p = np + 2;
	}
	var len1 = f.length - p;
	r_b += len1 == null ? HxOverrides.substr(f,p,null) : HxOverrides.substr(f,p,len1);
	return r_b;
};
DateTools.format = function(d,f) {
	return DateTools.__format(d,f);
};
var EReg = function(r,opt) {
	this.r = new RegExp(r,opt.split("u").join(""));
};
EReg.__name__ = "EReg";
EReg.prototype = {
	match: function(s) {
		if(this.r.global) {
			this.r.lastIndex = 0;
		}
		this.r.m = this.r.exec(s);
		this.r.s = s;
		return this.r.m != null;
	}
	,matched: function(n) {
		if(this.r.m != null && n >= 0 && n < this.r.m.length) {
			return this.r.m[n];
		} else {
			throw new js__$Boot_HaxeError("EReg::matched");
		}
	}
	,__class__: EReg
};
var HtmlTools = function() { };
HtmlTools.__name__ = "HtmlTools";
HtmlTools.q = function(query) {
	return window.document.querySelector(query);
};
HtmlTools.elPos = function(collection,el) {
	var _g = 0;
	var _g1 = collection.length;
	while(_g < _g1) {
		var i = _g++;
		if(collection.item(i) == el) {
			return i;
		}
	}
	return -1;
};
var HxOverrides = function() { };
HxOverrides.__name__ = "HxOverrides";
HxOverrides.dateStr = function(date) {
	var m1 = date.getMonth() + 1;
	var d = date.getDate();
	var h = date.getHours();
	var mi = date.getMinutes();
	var s = date.getSeconds();
	return date.getFullYear() + "-" + (m1 < 10 ? "0" + m1 : "" + m1) + "-" + (d < 10 ? "0" + d : "" + d) + " " + (h < 10 ? "0" + h : "" + h) + ":" + (mi < 10 ? "0" + mi : "" + mi) + ":" + (s < 10 ? "0" + s : "" + s);
};
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) {
		return undefined;
	}
	return x;
};
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var Lambda = function() { };
Lambda.__name__ = "Lambda";
Lambda.array = function(it) {
	var a = [];
	var i = $getIterator(it);
	while(i.hasNext()) {
		var i1 = i.next();
		a.push(i1);
	}
	return a;
};
Lambda.exists = function(it,f) {
	var x = $getIterator(it);
	while(x.hasNext()) {
		var x1 = x.next();
		if(f(x1)) {
			return true;
		}
	}
	return false;
};
Lambda.find = function(it,f) {
	var v = $getIterator(it);
	while(v.hasNext()) {
		var v1 = v.next();
		if(f(v1)) {
			return v1;
		}
	}
	return null;
};
var Main = function() {
};
Main.__name__ = "Main";
Main.main = function() {
	new Main().start();
};
Main.prototype = {
	start: function() {
		Data.libraryItems = [new Book({ rfid : "ITEM787", title : "Anna Karenina", loanTimeDays : 21}),new Bluray({ rfid : "ITEM788", title : "War and Peace", loanTimeDays : 14, length : 168}),new Book({ rfid : "ITEM789", title : "Master and Man", loanTimeDays : 21})];
		Data.libraryCards = [new LibraryCard({ rfid : "CARD54321", name : "Leo Tolstoy", pin : "1234"})];
		Data.libraryLoans = [];
		var bookshelf = Lambda.array(Data.libraryItems);
		var workspace = Lambda.array(Data.libraryCards);
		var scannerContents = [];
		var scanner = new gadgets_RfidScanner(function() {
			try {
				return haxe_ds_Option.Some((js_Boot.__cast(scannerContents[0] , RfidItem)).rfid);
			} catch( e ) {
				var e1 = ((e) instanceof js__$Boot_HaxeError) ? e.val : e;
				return haxe_ds_Option.None;
			}
		});
		var cardReaderContents = [];
		var cardReader = new gadgets_RfidScanner(function() {
			try {
				return haxe_ds_Option.Some((js_Boot.__cast(cardReaderContents[0] , RfidItem)).rfid);
			} catch( e2 ) {
				var e3 = ((e2) instanceof js__$Boot_HaxeError) ? e2.val : e2;
				return haxe_ds_Option.None;
			}
		});
		var printer = new gadgets_ReceiptPrinter();
		var screen = new views_ScreenView();
		var keypad = screen;
		var finishButtons = screen;
		new views_MainView(bookshelf,cardReaderContents,workspace,scannerContents,screen,printer).mount();
		var _g = new haxe_ds_StringMap();
		var key = "bookshelf";
		if(__map_reserved[key] != null) {
			_g.setReserved(key,bookshelf);
		} else {
			_g.h[key] = bookshelf;
		}
		var key1 = "card-reader";
		if(__map_reserved[key1] != null) {
			_g.setReserved(key1,cardReaderContents);
		} else {
			_g.h[key1] = cardReaderContents;
		}
		var key2 = "workspace";
		if(__map_reserved[key2] != null) {
			_g.setReserved(key2,workspace);
		} else {
			_g.h[key2] = workspace;
		}
		var key3 = "scanner";
		if(__map_reserved[key3] != null) {
			_g.setReserved(key3,scannerContents);
		} else {
			_g.h[key3] = scannerContents;
		}
		var surfaces = _g;
		new contexts_DragDropMechanics(surfaces).start();
		new contexts_LibraryBorrowMachine(scanner,cardReader,screen,printer,keypad,finishButtons).start();
	}
	,__class__: Main
};
Math.__name__ = "Math";
var Reflect = function() { };
Reflect.__name__ = "Reflect";
Reflect.field = function(o,field) {
	try {
		return o[field];
	} catch( e ) {
		var e1 = ((e) instanceof js__$Boot_HaxeError) ? e.val : e;
		return null;
	}
};
var SingleEventHandler = function() {
};
SingleEventHandler.__name__ = "SingleEventHandler";
SingleEventHandler.__interfaces__ = [haxecontracts_HaxeContracts];
SingleEventHandler.prototype = {
	get_trigger: function() {
		try {
			if(this._trigger == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException(this.removePos != null ? "Event removed before triggered, at " + this.posStr(this.removePos) : this.setPos != null ? "Event already triggered. Set at " + this.posStr(this.setPos) : "Event not set.",this,[],null,{ fileName : "lib/SingleEventHandler.hx", lineNumber : 25, className : "SingleEventHandler", methodName : "get_trigger"}));
			}
		} catch( e ) {
			var e1 = ((e) instanceof js__$Boot_HaxeError) ? e.val : e;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException(this.removePos != null ? "Event removed before triggered, at " + this.posStr(this.removePos) : this.setPos != null ? "Event already triggered. Set at " + this.posStr(this.setPos) : "Event not set.",this,[],e1,{ fileName : "lib/SingleEventHandler.hx", lineNumber : 25, className : "SingleEventHandler", methodName : "get_trigger"}));
		}
		var t = this._trigger;
		this._trigger = null;
		return t;
	}
	,set: function(event,pos) {
		try {
			if(event == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [event != null]",this,[event,pos],null,{ fileName : "lib/SingleEventHandler.hx", lineNumber : 36, className : "SingleEventHandler", methodName : "set"}));
			}
		} catch( e ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [event != null]",this,[event,pos],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "lib/SingleEventHandler.hx", lineNumber : 36, className : "SingleEventHandler", methodName : "set"}));
		}
		try {
			if(!(this._trigger == null || this._trigger == event)) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Event already set at " + this.posStr(this.setPos) + " (Attempted to set at " + this.posStr(pos) + ")",this,[event,pos],null,{ fileName : "lib/SingleEventHandler.hx", lineNumber : 38, className : "SingleEventHandler", methodName : "set"}));
			}
		} catch( e1 ) {
			var e2 = ((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Event already set at " + this.posStr(this.setPos) + " (Attempted to set at " + this.posStr(pos) + ")",this,[event,pos],e2,{ fileName : "lib/SingleEventHandler.hx", lineNumber : 38, className : "SingleEventHandler", methodName : "set"}));
		}
		this._trigger = event;
		this.setPos = pos;
		this.removePos = null;
	}
	,remove: function(event,pos) {
		try {
			if(event == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [event != null]",this,[event,pos],null,{ fileName : "lib/SingleEventHandler.hx", lineNumber : 47, className : "SingleEventHandler", methodName : "remove"}));
			}
		} catch( e ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [event != null]",this,[event,pos],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "lib/SingleEventHandler.hx", lineNumber : 47, className : "SingleEventHandler", methodName : "remove"}));
		}
		try {
			if(this._trigger != event) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException(this.setPos == null ? "Event not set before removal. Removed at " + this.posStr(pos) : "Event not same as the one registered at " + this.posStr(this.setPos) + " (Attempted to remove at " + this.posStr(pos) + ")",this,[event,pos],null,{ fileName : "lib/SingleEventHandler.hx", lineNumber : 49, className : "SingleEventHandler", methodName : "remove"}));
			}
		} catch( e1 ) {
			var e2 = ((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException(this.setPos == null ? "Event not set before removal. Removed at " + this.posStr(pos) : "Event not same as the one registered at " + this.posStr(this.setPos) + " (Attempted to remove at " + this.posStr(pos) + ")",this,[event,pos],e2,{ fileName : "lib/SingleEventHandler.hx", lineNumber : 49, className : "SingleEventHandler", methodName : "remove"}));
		}
		this._trigger = null;
		this.setPos = null;
		this.removePos = pos;
	}
	,posStr: function(p) {
		return p.fileName + ":" + p.lineNumber;
	}
	,__class__: SingleEventHandler
};
var Std = function() { };
Std.__name__ = "Std";
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
Std.parseInt = function(x) {
	if(x != null) {
		var _g = 0;
		var _g1 = x.length;
		while(_g < _g1) {
			var i = _g++;
			var c = x.charCodeAt(i);
			if(c <= 8 || c >= 14 && c != 32 && c != 45) {
				var v = parseInt(x, (x[(i + 1)]=="x" || x[(i + 1)]=="X") ? 16 : 10);
				if(isNaN(v)) {
					return null;
				} else {
					return v;
				}
			}
		}
	}
	return null;
};
var StringTools = function() { };
StringTools.__name__ = "StringTools";
StringTools.isSpace = function(s,pos) {
	var c = HxOverrides.cca(s,pos);
	if(!(c > 8 && c < 14)) {
		return c == 32;
	} else {
		return true;
	}
};
StringTools.ltrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,r)) ++r;
	if(r > 0) {
		return HxOverrides.substr(s,r,l - r);
	} else {
		return s;
	}
};
StringTools.rtrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,l - r - 1)) ++r;
	if(r > 0) {
		return HxOverrides.substr(s,0,l - r);
	} else {
		return s;
	}
};
StringTools.trim = function(s) {
	return StringTools.ltrim(StringTools.rtrim(s));
};
StringTools.lpad = function(s,c,l) {
	if(c.length <= 0) {
		return s;
	}
	var buf_b = "";
	l -= s.length;
	while(buf_b.length < l) buf_b += c == null ? "null" : "" + c;
	buf_b += s == null ? "null" : "" + s;
	return buf_b;
};
StringTools.rpad = function(s,c,l) {
	if(c.length <= 0) {
		return s;
	}
	var buf_b = "";
	buf_b += s == null ? "null" : "" + s;
	while(buf_b.length < l) buf_b += c == null ? "null" : "" + c;
	return buf_b;
};
var Type = function() { };
Type.__name__ = "Type";
Type.enumEq = function(a,b) {
	if(a == b) {
		return true;
	}
	try {
		var e = a.__enum__;
		if(e == null || e != b.__enum__) {
			return false;
		}
		if(a._hx_index != b._hx_index) {
			return false;
		}
		var enm = $hxEnums[e];
		var ctorName = enm.__constructs__[a._hx_index];
		var params = enm[ctorName].__params__;
		var _g = 0;
		while(_g < params.length) {
			var f = params[_g];
			++_g;
			if(!Type.enumEq(a[f],b[f])) {
				return false;
			}
		}
	} catch( e1 ) {
		var e2 = ((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1;
		return false;
	}
	return true;
};
var contexts_BorrowLoanItemStatus = $hxEnums["contexts.BorrowLoanItemStatus"] = { __ename__ : true, __constructs__ : ["Ok","ItemAlreadyBorrowed","InvalidBorrower","InvalidLoanItem"]
	,Ok: ($_=function(loan) { return {_hx_index:0,loan:loan,__enum__:"contexts.BorrowLoanItemStatus",toString:$estr}; },$_.__params__ = ["loan"],$_)
	,ItemAlreadyBorrowed: {_hx_index:1,__enum__:"contexts.BorrowLoanItemStatus",toString:$estr}
	,InvalidBorrower: {_hx_index:2,__enum__:"contexts.BorrowLoanItemStatus",toString:$estr}
	,InvalidLoanItem: {_hx_index:3,__enum__:"contexts.BorrowLoanItemStatus",toString:$estr}
};
var dci_Context = function() { };
dci_Context.__name__ = "dci.Context";
dci_Context.__isInterface__ = true;
var contexts_BorrowLoanItem = function(loanItem,borrower) {
	this.listOfLibraryCards = Data.libraryCards;
	this.listOfItems = Data.libraryItems;
	this.listOfLoans = Data.libraryLoans;
	this.loanItem = loanItem;
	this.borrower = borrower;
	this.librarian = this;
};
contexts_BorrowLoanItem.__name__ = "contexts.BorrowLoanItem";
contexts_BorrowLoanItem.__interfaces__ = [dci_Context];
contexts_BorrowLoanItem.prototype = {
	borrow: function() {
		return this.librarian__checkBorrowerId();
	}
	,librarian__checkBorrowerId: function() {
		var id = this.borrower__id();
		if(!this.listOfLibraryCards__hasBorrowerId(id)) {
			return contexts_BorrowLoanItemStatus.InvalidBorrower;
		} else {
			return this.librarian__checkLoanItemId();
		}
	}
	,librarian__checkLoanItemId: function() {
		var id = this.loanItem__id();
		if(!this.listOfItems__hasLoanItem(id)) {
			return contexts_BorrowLoanItemStatus.InvalidLoanItem;
		} else if(this.listOfLoans__hasLoanItemAlready(id)) {
			return contexts_BorrowLoanItemStatus.ItemAlreadyBorrowed;
		} else {
			return this.librarian__addLoan();
		}
	}
	,librarian__addLoan: function() {
		var loanTime = this.loanItem__loanTime();
		var loan = new LibraryLoan({ borrowerRfid : this.borrower__id(), loanItemRfid : this.loanItem__id(), created : new Date(), returnDate : new Date(new Date().getTime() + loanTime * 24 * 60 * 60 * 1000)});
		this.listOfLoans__addLoan(loan);
		return contexts_BorrowLoanItemStatus.Ok(loan);
	}
	,listOfLoans__hasLoanItemAlready: function(id) {
		return Lambda.exists(this.listOfLoans,function(loan) {
			if(loan.loanItemRfid == id) {
				return loan.returnDate.getTime() > new Date().getTime();
			} else {
				return false;
			}
		});
	}
	,listOfLoans__addLoan: function(loan) {
		this.listOfLoans.push(loan);
	}
	,listOfLibraryCards__hasBorrowerId: function(id) {
		return Lambda.exists(this.listOfLibraryCards,function(card) {
			return card.rfid == id;
		});
	}
	,listOfItems__hasLoanItem: function(id) {
		return Lambda.exists(this.listOfItems,function(item) {
			return item.rfid == id;
		});
	}
	,loanItem__id: function() {
		return this.loanItem.rfid;
	}
	,loanItem__loanTime: function() {
		return this.loanItem.loanTimeDays;
	}
	,borrower__id: function() {
		return this.borrower.rfid;
	}
	,__class__: contexts_BorrowLoanItem
};
var contexts_DragDropMechanics = function(surfaces) {
	try {
		if(surfaces == null) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [surfaces != null]",this,[surfaces],null,{ fileName : "src/contexts/DragDropMechanics.hx", lineNumber : 40, className : "contexts.DragDropMechanics", methodName : "new"}));
		}
	} catch( e ) {
		throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [surfaces != null]",this,[surfaces],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "src/contexts/DragDropMechanics.hx", lineNumber : 40, className : "contexts.DragDropMechanics", methodName : "new"}));
	}
	this.surfaces = surfaces;
};
contexts_DragDropMechanics.__name__ = "contexts.DragDropMechanics";
contexts_DragDropMechanics.__interfaces__ = [haxecontracts_HaxeContracts];
contexts_DragDropMechanics.prototype = {
	start: function() {
		try {
			if(Reflect.field(window,"dragula") == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [Reflect.field(Browser.window, \"dragula\") != null]",this,[],null,{ fileName : "src/contexts/DragDropMechanics.hx", lineNumber : 45, className : "contexts.DragDropMechanics", methodName : "start"}));
			}
		} catch( e ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [Reflect.field(Browser.window, \"dragula\") != null]",this,[],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "src/contexts/DragDropMechanics.hx", lineNumber : 45, className : "contexts.DragDropMechanics", methodName : "start"}));
		}
		var dragula = Reflect.field(window,"dragula");
		var _g = [];
		var id = this.surfaces.keys();
		while(id.hasNext()) {
			var id1 = id.next();
			_g.push(HtmlTools.q("#" + id1));
		}
		this.drake = dragula(_g,{ accepts : $bind(this,this.acceptsDrop)}).on("drag",$bind(this,this.onDrag)).on("drop",$bind(this,this.onDrop));
	}
	,acceptsDrop: function(droppedItem,targetElement) {
		try {
			if(droppedItem == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [droppedItem != null]",this,[droppedItem,targetElement],null,{ fileName : "src/contexts/DragDropMechanics.hx", lineNumber : 58, className : "contexts.DragDropMechanics", methodName : "acceptsDrop"}));
			}
		} catch( e ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [droppedItem != null]",this,[droppedItem,targetElement],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "src/contexts/DragDropMechanics.hx", lineNumber : 58, className : "contexts.DragDropMechanics", methodName : "acceptsDrop"}));
		}
		try {
			if(targetElement.id.length <= 0) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [targetElement.id.length > 0]",this,[droppedItem,targetElement],null,{ fileName : "src/contexts/DragDropMechanics.hx", lineNumber : 59, className : "contexts.DragDropMechanics", methodName : "acceptsDrop"}));
			}
		} catch( e1 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [targetElement.id.length > 0]",this,[droppedItem,targetElement],((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1,{ fileName : "src/contexts/DragDropMechanics.hx", lineNumber : 59, className : "contexts.DragDropMechanics", methodName : "acceptsDrop"}));
		}
		switch(targetElement.id) {
		case "card-reader":
			var key = targetElement.id;
			var _this = this.surfaces;
			if((__map_reserved[key] != null ? _this.getReserved(key) : _this.h[key]).length < 1) {
				return droppedItem.classList.contains("card");
			} else {
				return false;
			}
			break;
		case "scanner":
			var key1 = targetElement.id;
			var _this1 = this.surfaces;
			return (__map_reserved[key1] != null ? _this1.getReserved(key1) : _this1.h[key1]).length < 1;
		default:
			if(droppedItem.classList.contains("card")) {
				return targetElement.id != "bookshelf";
			} else {
				return targetElement.id != "card-reader";
			}
		}
	}
	,onDrag: function(el,sourceEl) {
		try {
			if(el == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [el != null]",this,[el,sourceEl],null,{ fileName : "src/contexts/DragDropMechanics.hx", lineNumber : 82, className : "contexts.DragDropMechanics", methodName : "onDrag"}));
			}
		} catch( e ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [el != null]",this,[el,sourceEl],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "src/contexts/DragDropMechanics.hx", lineNumber : 82, className : "contexts.DragDropMechanics", methodName : "onDrag"}));
		}
		try {
			var key = sourceEl.id;
			var _this = this.surfaces;
			if(!(__map_reserved[key] != null ? _this.existsReserved(key) : _this.h.hasOwnProperty(key))) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("No surface found: " + sourceEl.id,this,[el,sourceEl],null,{ fileName : "src/contexts/DragDropMechanics.hx", lineNumber : 83, className : "contexts.DragDropMechanics", methodName : "onDrag"}));
			}
		} catch( e1 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("No surface found: " + sourceEl.id,this,[el,sourceEl],((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1,{ fileName : "src/contexts/DragDropMechanics.hx", lineNumber : 83, className : "contexts.DragDropMechanics", methodName : "onDrag"}));
		}
		var key1 = sourceEl.id;
		var _this1 = this.surfaces;
		var surface = __map_reserved[key1] != null ? _this1.getReserved(key1) : _this1.h[key1];
		var pos = HtmlTools.elPos(sourceEl.children,el);
		try {
			if(pos < 0) {
				throw new js__$Boot_HaxeError(false);
			}
		} catch( e2 ) {
			var e3 = ((e2) instanceof js__$Boot_HaxeError) ? e2.val : e2;
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Item not found in surface " + sourceEl.id,this,null,typeof(e3) == "boolean" ? null : e3,{ fileName : "src/contexts/DragDropMechanics.hx", lineNumber : 87, className : "contexts.DragDropMechanics", methodName : "onDrag"}));
		}
		this.dragData = { source : surface, sourcePos : pos};
	}
	,onDrop: function(el,targetEl,_,sibling) {
		try {
			if(this.dragData == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [this.dragData != null]",this,[el,targetEl,_,sibling],null,{ fileName : "src/contexts/DragDropMechanics.hx", lineNumber : 98, className : "contexts.DragDropMechanics", methodName : "onDrop"}));
			}
		} catch( e ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [this.dragData != null]",this,[el,targetEl,_,sibling],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "src/contexts/DragDropMechanics.hx", lineNumber : 98, className : "contexts.DragDropMechanics", methodName : "onDrop"}));
		}
		try {
			if(el == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [el != null]",this,[el,targetEl,_,sibling],null,{ fileName : "src/contexts/DragDropMechanics.hx", lineNumber : 99, className : "contexts.DragDropMechanics", methodName : "onDrop"}));
			}
		} catch( e1 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [el != null]",this,[el,targetEl,_,sibling],((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1,{ fileName : "src/contexts/DragDropMechanics.hx", lineNumber : 99, className : "contexts.DragDropMechanics", methodName : "onDrop"}));
		}
		try {
			var key = targetEl.id;
			var _this = this.surfaces;
			if(!(__map_reserved[key] != null ? _this.existsReserved(key) : _this.h.hasOwnProperty(key))) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("No surface found: " + targetEl.id,this,[el,targetEl,_,sibling],null,{ fileName : "src/contexts/DragDropMechanics.hx", lineNumber : 100, className : "contexts.DragDropMechanics", methodName : "onDrop"}));
			}
		} catch( e2 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("No surface found: " + targetEl.id,this,[el,targetEl,_,sibling],((e2) instanceof js__$Boot_HaxeError) ? e2.val : e2,{ fileName : "src/contexts/DragDropMechanics.hx", lineNumber : 100, className : "contexts.DragDropMechanics", methodName : "onDrop"}));
		}
		var key1 = targetEl.id;
		var _this1 = this.surfaces;
		var target = __map_reserved[key1] != null ? _this1.getReserved(key1) : _this1.h[key1];
		var targetPos = sibling == null ? targetEl.children.length - 1 : HtmlTools.elPos(targetEl.children,sibling) - 1;
		var removed = this.dragData.source.splice(this.dragData.sourcePos,1);
		target.splice(targetPos,0,removed[0]);
		this.dragData = null;
		this.drake.cancel(true);
		m.redraw();
	}
	,__class__: contexts_DragDropMechanics
};
var contexts_LibraryBorrowMachine = function(scanner,cardReader,screen,printer,keypad,finishButtons) {
	this.scanner = scanner;
	this.cardReader = cardReader;
	this.screen = screen;
	this.printer = printer;
	this.keypad = keypad;
	this.finishButtons = finishButtons;
	this.library = Data;
	this.scannedItems = [];
};
contexts_LibraryBorrowMachine.__name__ = "contexts.LibraryBorrowMachine";
contexts_LibraryBorrowMachine.__interfaces__ = [dci_Context];
contexts_LibraryBorrowMachine.prototype = {
	start: function() {
		this.resetState();
		this.screen__displayWelcome();
		this.cardReader__waitForCardChange();
	}
	,restart: function() {
		this.resetState();
		this.screen__displayThankYouMessage();
		this.cardReader__waitForCardChange();
	}
	,resetState: function() {
		this.scannedItems__clearItems();
		this.pinAttemptsLeft = contexts_LibraryBorrowMachine.maxPinAttempts;
		this.authorizedCard = null;
		this.lastScannedRfid = haxe_ds_Option.None;
	}
	,cardReader__waitForCardChange: function() {
		this.cardReader.scanRfid($bind(this,this.cardReader__rfidScanned));
	}
	,cardReader__rfidScanned: function(data) {
		switch(data._hx_index) {
		case 0:
			var rfid = data.v;
			this.cardReader__createWaitLoopForCardRemoval();
			var card = this.library__card(rfid);
			if(card != null) {
				this.screen__displayEnterPin();
			} else {
				this.screen__displayInvalidCard();
			}
			break;
		case 1:
			this.cardReader__waitForCardChange();
			break;
		}
	}
	,cardReader__createWaitLoopForCardRemoval: function() {
		var _gthis = this;
		var removeCardLoop = new haxe_Timer(50);
		removeCardLoop.run = function() {
			_gthis.cardReader.scanRfid(function(data) {
				if(Type.enumEq(data,haxe_ds_Option.None)) {
					removeCardLoop.stop();
					_gthis.restart();
				}
			});
		};
	}
	,cardReader__validatePin: function(pin) {
		var _gthis = this;
		this.cardReader.scanRfid(function(data) {
			switch(data._hx_index) {
			case 0:
				var rfid = data.v;
				var card = _gthis.library__card(rfid);
				if(card == null) {
					_gthis.screen__displayInvalidCard();
				} else if(card.pin == pin) {
					_gthis.authorizedCard = card;
					_gthis.screen__displayScannedItems();
					_gthis.scanner__waitForItem();
				} else if(--_gthis.pinAttemptsLeft > 0) {
					_gthis.screen__displayEnterPin();
				} else {
					_gthis.screen__displayTooManyInvalidPin();
				}
				break;
			case 1:
				break;
			}
		});
	}
	,scanner__waitForItem: function() {
		this.scanner.scanRfid($bind(this,this.scanner__readLoanItem));
	}
	,scanner__readLoanItem: function(rfid) {
		if(this.authorizedCard == null) {
			return;
		}
		if(Type.enumEq(rfid,this.lastScannedRfid)) {
			this.scanner__waitForItem();
			return;
		} else {
			this.lastScannedRfid = rfid;
		}
		switch(rfid._hx_index) {
		case 0:
			var rfid1 = rfid.v;
			if(this.scannedItems__alreadyScanned(rfid1)) {
				this.scanner__waitForItem();
				return;
			}
			var item = this.library__item(rfid1);
			if(item == null) {
				this.scanner__waitForItem();
				return;
			}
			var _g = new contexts_BorrowLoanItem(item,this.authorizedCard).borrow();
			switch(_g._hx_index) {
			case 0:
				var loan = _g.loan;
				this.scannedItems__addItem(new ReceiptItem(item,loan.returnDate));
				this.screen__displayScannedItems();
				this.scanner__waitForItem();
				break;
			case 1:
				this.screen__displayAlreadyBorrowedMessage();
				this.scanner__waitForItem();
				break;
			case 2:
				this.screen__displayInvalidCard();
				break;
			case 3:
				this.screen__displayInvalidLoanItemMessage();
				this.scanner__waitForItem();
				break;
			}
			break;
		case 1:
			this.scanner__waitForItem();
			break;
		}
	}
	,scannedItems__addItem: function(item) {
		this.scannedItems.push(item);
	}
	,scannedItems__clearItems: function() {
		this.scannedItems.splice(0,this.scannedItems.length);
	}
	,scannedItems__alreadyScanned: function(rfid) {
		return Lambda.exists(this.scannedItems,function(scannedItem) {
			return scannedItem.item.rfid == rfid;
		});
	}
	,screen__displayWelcome: function() {
		this.screen.display(views_ScreenState.Welcome);
	}
	,screen__displayThankYouMessage: function() {
		this.screen.displayMessage(views_ScreenState.ThankYou,4000,views_ScreenState.Welcome);
	}
	,screen__displayEnterPin: function() {
		this.keypad__waitForEnterPin();
		this.screen.display(views_ScreenState.EnterPin({ previousAttemptFailed : this.pinAttemptsLeft < 3}));
	}
	,screen__displayScannedItems: function() {
		this.finishButtons__waitForFinishClick();
		this.screen.display(views_ScreenState.DisplayBorrowedItems(this.scannedItems));
	}
	,screen__displayTooManyInvalidPin: function() {
		this.screen.display(views_ScreenState.TooManyInvalidPin);
	}
	,screen__displayInvalidCard: function() {
		this.screen.display(views_ScreenState.InvalidCard);
	}
	,screen__displayInvalidLoanItemMessage: function() {
		this.screen.displayMessage(views_ScreenState.InvalidLoanItem,3000);
	}
	,screen__displayAlreadyBorrowedMessage: function() {
		this.screen.displayMessage(views_ScreenState.ItemAlreadyBorrowed,3000);
	}
	,screen__displayDontForgetLibraryCard: function() {
		this.screen.display(views_ScreenState.DontForgetLibraryCard);
	}
	,finishButtons__waitForFinishClick: function() {
		this.finishButtons.onFinishWithoutReceiptClicked($bind(this,this.screen__displayDontForgetLibraryCard),{ fileName : "src/contexts/LibraryBorrowMachine.hx", lineNumber : 227, className : "contexts.LibraryBorrowMachine", methodName : "finishButtons__waitForFinishClick"});
		this.finishButtons.onFinishWithReceiptClicked($bind(this,this.printer__printReceipt),{ fileName : "src/contexts/LibraryBorrowMachine.hx", lineNumber : 228, className : "contexts.LibraryBorrowMachine", methodName : "finishButtons__waitForFinishClick"});
	}
	,keypad__waitForEnterPin: function() {
		this.keypad.onPinCodeEntered($bind(this,this.cardReader__validatePin),{ fileName : "src/contexts/LibraryBorrowMachine.hx", lineNumber : 236, className : "contexts.LibraryBorrowMachine", methodName : "keypad__waitForEnterPin"});
	}
	,printer__printReceipt: function() {
		var _gthis = this;
		var buffer = [DateTools.format(new Date(),"%Y-%m-%d"),""];
		var scanned = $getIterator(this.scannedItems);
		while(scanned.hasNext()) {
			var scanned1 = scanned.next();
			buffer.push(scanned1.item.title);
			var tmp = "Return on " + DateTools.format(scanned1.returnDate,"%Y-%m-%d");
			buffer.push(tmp);
			buffer.push("");
		}
		var timer = new haxe_Timer(80);
		timer.run = function() {
			_gthis.printer.print(buffer.pop());
			if(buffer.length == 0) {
				timer.stop();
				_gthis.printer.cutPaper();
				_gthis.screen__displayDontForgetLibraryCard();
			}
		};
	}
	,library__item: function(rfid) {
		return Lambda.find(this.library.libraryItems,function(loanItem) {
			return loanItem.rfid == rfid;
		});
	}
	,library__card: function(rfid) {
		return Lambda.find(this.library.libraryCards,function(libraryCard) {
			return libraryCard.rfid == rfid;
		});
	}
	,__class__: contexts_LibraryBorrowMachine
};
var dataclass_DataClassException = function(dataClass,data,errors) {
	this.dataClass = dataClass;
	this.data = data;
	this.errors = errors;
};
dataclass_DataClassException.__name__ = "dataclass.DataClassException";
dataclass_DataClassException.prototype = {
	toString: function() {
		var c = js_Boot.getClass(this.dataClass);
		return c.__name__ + " invalid data: " + this.errors.toString();
	}
	,__class__: dataclass_DataClassException
};
var mithril_Mithril = function() { };
mithril_Mithril.__name__ = "mithril.Mithril";
mithril_Mithril.__isInterface__ = true;
var gadgets_ReceiptPrinter = function() {
	this.buffer = [];
	this.paperIsCut = false;
};
gadgets_ReceiptPrinter.__name__ = "gadgets.ReceiptPrinter";
gadgets_ReceiptPrinter.__interfaces__ = [mithril_Mithril,haxecontracts_HaxeContracts];
gadgets_ReceiptPrinter.prototype = {
	get_receipt: function() {
		return this.buffer;
	}
	,print: function(line) {
		if(this.paperIsCut) {
			this.buffer = [];
			this.paperIsCut = false;
		}
		this.buffer.unshift(line);
		m.redraw();
		try {
			if(this.buffer == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [buffer != null]",this,[line],null,{ fileName : "src/gadgets/ReceiptPrinter.hx", lineNumber : 43, className : "gadgets.ReceiptPrinter", methodName : "print"}));
			}
		} catch( e ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [buffer != null]",this,[line],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "src/gadgets/ReceiptPrinter.hx", lineNumber : 43, className : "gadgets.ReceiptPrinter", methodName : "print"}));
		}
	}
	,cutPaper: function() {
		this.paperIsCut = true;
	}
	,view: function() {
		if(arguments.length > 0 && arguments[0].tag != this) return arguments[0].tag.view.apply(arguments[0].tag, arguments);
		try {
			if(this.buffer == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [buffer != null]",this,[],null,{ fileName : "src/gadgets/ReceiptPrinter.hx", lineNumber : 43, className : "gadgets.ReceiptPrinter", methodName : "view"}));
			}
		} catch( e ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [buffer != null]",this,[],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "src/gadgets/ReceiptPrinter.hx", lineNumber : 43, className : "gadgets.ReceiptPrinter", methodName : "view"}));
		}
		var _g7 = [];
		var s = $getIterator(this.get_receipt());
		while(s.hasNext()) {
			var s1 = s.next();
			_g7.push(m.m("p",s1 == "" ? m.trust("&nbsp;") : s1));
		}
		var __contract_output = m.m(".box",m.m(".slot",m.m(".paper",_g7)));
		return __contract_output;
	}
	,__class__: gadgets_ReceiptPrinter
};
var gadgets_RfidScanner = function(returnRfid) {
	this.returnRfid = returnRfid;
	this.lastScanned = haxe_ds_Option.None;
	try {
		if(returnRfid == null) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [returnRfid != null]",this,[returnRfid],null,{ fileName : "src/gadgets/RfidScanner.hx", lineNumber : 48, className : "gadgets.RfidScanner", methodName : "new"}));
		}
	} catch( e ) {
		throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [returnRfid != null]",this,[returnRfid],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "src/gadgets/RfidScanner.hx", lineNumber : 48, className : "gadgets.RfidScanner", methodName : "new"}));
	}
	try {
		if(this.lastScanned == null) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [lastScanned != null]",this,[returnRfid],null,{ fileName : "src/gadgets/RfidScanner.hx", lineNumber : 49, className : "gadgets.RfidScanner", methodName : "new"}));
		}
	} catch( e1 ) {
		throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [lastScanned != null]",this,[returnRfid],((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1,{ fileName : "src/gadgets/RfidScanner.hx", lineNumber : 49, className : "gadgets.RfidScanner", methodName : "new"}));
	}
};
gadgets_RfidScanner.__name__ = "gadgets.RfidScanner";
gadgets_RfidScanner.__interfaces__ = [haxecontracts_HaxeContracts];
gadgets_RfidScanner.prototype = {
	scanRfid: function(callback) {
		var _gthis = this;
		haxe_Timer.delay(function() {
			var scanned = _gthis.returnRfid();
			callback(scanned);
			_gthis.lastScanned = scanned;
		},0);
		try {
			if(this.returnRfid == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [returnRfid != null]",this,[callback],null,{ fileName : "src/gadgets/RfidScanner.hx", lineNumber : 48, className : "gadgets.RfidScanner", methodName : "scanRfid"}));
			}
		} catch( e ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [returnRfid != null]",this,[callback],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "src/gadgets/RfidScanner.hx", lineNumber : 48, className : "gadgets.RfidScanner", methodName : "scanRfid"}));
		}
		try {
			if(this.lastScanned == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [lastScanned != null]",this,[callback],null,{ fileName : "src/gadgets/RfidScanner.hx", lineNumber : 49, className : "gadgets.RfidScanner", methodName : "scanRfid"}));
			}
		} catch( e1 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [lastScanned != null]",this,[callback],((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1,{ fileName : "src/gadgets/RfidScanner.hx", lineNumber : 49, className : "gadgets.RfidScanner", methodName : "scanRfid"}));
		}
	}
	,lastScannedRfid: function() {
		try {
			if(this.returnRfid == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [returnRfid != null]",this,[],null,{ fileName : "src/gadgets/RfidScanner.hx", lineNumber : 48, className : "gadgets.RfidScanner", methodName : "lastScannedRfid"}));
			}
		} catch( e ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [returnRfid != null]",this,[],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "src/gadgets/RfidScanner.hx", lineNumber : 48, className : "gadgets.RfidScanner", methodName : "lastScannedRfid"}));
		}
		try {
			if(this.lastScanned == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [lastScanned != null]",this,[],null,{ fileName : "src/gadgets/RfidScanner.hx", lineNumber : 49, className : "gadgets.RfidScanner", methodName : "lastScannedRfid"}));
			}
		} catch( e1 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [lastScanned != null]",this,[],((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1,{ fileName : "src/gadgets/RfidScanner.hx", lineNumber : 49, className : "gadgets.RfidScanner", methodName : "lastScannedRfid"}));
		}
		var __contract_output = this.lastScanned;
		return __contract_output;
	}
	,__class__: gadgets_RfidScanner
};
var haxe_StackItem = $hxEnums["haxe.StackItem"] = { __ename__ : true, __constructs__ : ["CFunction","Module","FilePos","Method","LocalFunction"]
	,CFunction: {_hx_index:0,__enum__:"haxe.StackItem",toString:$estr}
	,Module: ($_=function(m) { return {_hx_index:1,m:m,__enum__:"haxe.StackItem",toString:$estr}; },$_.__params__ = ["m"],$_)
	,FilePos: ($_=function(s,file,line,column) { return {_hx_index:2,s:s,file:file,line:line,column:column,__enum__:"haxe.StackItem",toString:$estr}; },$_.__params__ = ["s","file","line","column"],$_)
	,Method: ($_=function(classname,method) { return {_hx_index:3,classname:classname,method:method,__enum__:"haxe.StackItem",toString:$estr}; },$_.__params__ = ["classname","method"],$_)
	,LocalFunction: ($_=function(v) { return {_hx_index:4,v:v,__enum__:"haxe.StackItem",toString:$estr}; },$_.__params__ = ["v"],$_)
};
var haxe_CallStack = function() { };
haxe_CallStack.__name__ = "haxe.CallStack";
haxe_CallStack.getStack = function(e) {
	if(e == null) {
		return [];
	}
	var oldValue = Error.prepareStackTrace;
	Error.prepareStackTrace = function(error,callsites) {
		var stack = [];
		var _g = 0;
		while(_g < callsites.length) {
			var site = callsites[_g];
			++_g;
			if(haxe_CallStack.wrapCallSite != null) {
				site = haxe_CallStack.wrapCallSite(site);
			}
			var method = null;
			var fullName = site.getFunctionName();
			if(fullName != null) {
				var idx = fullName.lastIndexOf(".");
				if(idx >= 0) {
					var className = HxOverrides.substr(fullName,0,idx);
					var methodName = HxOverrides.substr(fullName,idx + 1,null);
					method = haxe_StackItem.Method(className,methodName);
				}
			}
			var fileName = site.getFileName();
			var fileAddr = fileName == null ? -1 : fileName.indexOf("file:");
			if(haxe_CallStack.wrapCallSite != null && fileAddr > 0) {
				fileName = HxOverrides.substr(fileName,fileAddr + 6,null);
			}
			stack.push(haxe_StackItem.FilePos(method,fileName,site.getLineNumber(),site.getColumnNumber()));
		}
		return stack;
	};
	var a = haxe_CallStack.makeStack(e.stack);
	Error.prepareStackTrace = oldValue;
	return a;
};
haxe_CallStack.callStack = function() {
	try {
		throw new Error();
	} catch( e ) {
		var e1 = ((e) instanceof js__$Boot_HaxeError) ? e.val : e;
		var a = haxe_CallStack.getStack(e);
		a.shift();
		return a;
	}
};
haxe_CallStack.makeStack = function(s) {
	if(s == null) {
		return [];
	} else if(typeof(s) == "string") {
		var stack = s.split("\n");
		if(stack[0] == "Error") {
			stack.shift();
		}
		var m1 = [];
		var rie10 = new EReg("^   at ([A-Za-z0-9_. ]+) \\(([^)]+):([0-9]+):([0-9]+)\\)$","");
		var _g = 0;
		while(_g < stack.length) {
			var line = stack[_g];
			++_g;
			if(rie10.match(line)) {
				var path = rie10.matched(1).split(".");
				var meth = path.pop();
				var file = rie10.matched(2);
				var line1 = Std.parseInt(rie10.matched(3));
				var column = Std.parseInt(rie10.matched(4));
				m1.push(haxe_StackItem.FilePos(meth == "Anonymous function" ? haxe_StackItem.LocalFunction() : meth == "Global code" ? null : haxe_StackItem.Method(path.join("."),meth),file,line1,column));
			} else {
				m1.push(haxe_StackItem.Module(StringTools.trim(line)));
			}
		}
		return m1;
	} else {
		return s;
	}
};
var haxe_IMap = function() { };
haxe_IMap.__name__ = "haxe.IMap";
haxe_IMap.__isInterface__ = true;
var haxe_Timer = function(time_ms) {
	var me = this;
	this.id = setInterval(function() {
		me.run();
	},time_ms);
};
haxe_Timer.__name__ = "haxe.Timer";
haxe_Timer.delay = function(f,time_ms) {
	var t = new haxe_Timer(time_ms);
	t.run = function() {
		t.stop();
		f();
	};
	return t;
};
haxe_Timer.prototype = {
	stop: function() {
		if(this.id == null) {
			return;
		}
		clearInterval(this.id);
		this.id = null;
	}
	,run: function() {
	}
	,__class__: haxe_Timer
};
var haxe_ds_Option = $hxEnums["haxe.ds.Option"] = { __ename__ : true, __constructs__ : ["Some","None"]
	,Some: ($_=function(v) { return {_hx_index:0,v:v,__enum__:"haxe.ds.Option",toString:$estr}; },$_.__params__ = ["v"],$_)
	,None: {_hx_index:1,__enum__:"haxe.ds.Option",toString:$estr}
};
var haxe_ds_StringMap = function() {
	this.h = { };
};
haxe_ds_StringMap.__name__ = "haxe.ds.StringMap";
haxe_ds_StringMap.__interfaces__ = [haxe_IMap];
haxe_ds_StringMap.prototype = {
	setReserved: function(key,value) {
		if(this.rh == null) {
			this.rh = { };
		}
		this.rh["$" + key] = value;
	}
	,getReserved: function(key) {
		if(this.rh == null) {
			return null;
		} else {
			return this.rh["$" + key];
		}
	}
	,existsReserved: function(key) {
		if(this.rh == null) {
			return false;
		}
		return this.rh.hasOwnProperty("$" + key);
	}
	,keys: function() {
		return HxOverrides.iter(this.arrayKeys());
	}
	,arrayKeys: function() {
		var out = [];
		for( var key in this.h ) {
		if(this.h.hasOwnProperty(key)) {
			out.push(key);
		}
		}
		if(this.rh != null) {
			for( var key in this.rh ) {
			if(key.charCodeAt(0) == 36) {
				out.push(key.substr(1));
			}
			}
		}
		return out;
	}
	,toString: function() {
		var s_b = "";
		s_b += "{";
		var keys = this.arrayKeys();
		var _g = 0;
		var _g1 = keys.length;
		while(_g < _g1) {
			var i = _g++;
			var k = keys[i];
			s_b += k == null ? "null" : "" + k;
			s_b += " => ";
			s_b += Std.string(Std.string(__map_reserved[k] != null ? this.getReserved(k) : this.h[k]));
			if(i < keys.length - 1) {
				s_b += ", ";
			}
		}
		s_b += "}";
		return s_b;
	}
	,__class__: haxe_ds_StringMap
};
var haxecontracts_Contract = function() { };
haxecontracts_Contract.__name__ = "haxecontracts.Contract";
haxecontracts_Contract.requires = function(condition,message) {
	if(message == null) {
		message = "Contract precondition failed.";
	}
	throw new js__$Boot_HaxeError(haxecontracts_Contract.implementationError);
};
haxecontracts_Contract.ensures = function(condition,message) {
	if(message == null) {
		message = "Contract postcondition failed.";
	}
	throw new js__$Boot_HaxeError(haxecontracts_Contract.implementationError);
};
haxecontracts_Contract.invariant = function(condition,message) {
	if(message == null) {
		message = "Contract invariant failed.";
	}
	throw new js__$Boot_HaxeError(haxecontracts_Contract.implementationError);
};
haxecontracts_Contract.get_result = function() {
	throw new js__$Boot_HaxeError(haxecontracts_Contract.implementationError);
};
haxecontracts_Contract.old = function(methodParameter) {
	throw new js__$Boot_HaxeError("Contract.old can only be called within Contract.ensures");
};
var haxecontracts_ContractException = function(message,object,$arguments,innerException,p) {
	if(message == null) {
		message = "";
	}
	this.message = message;
	this.object = object;
	this.arguments = $arguments == null ? [] : $arguments;
	this.pos = p;
	this.callStack = [];
	this.innerException = innerException;
	var _g = 0;
	var _g1 = haxe_CallStack.callStack();
	while(_g < _g1.length) {
		var s = _g1[_g];
		++_g;
		if(s._hx_index == 2) {
			var _g3 = s.column;
			var _g2 = s.line;
			var _g4 = s.s;
			var file = s.file;
			if(file != "haxecontracts/ContractException.hx") {
				this.callStack.push(s);
			}
		}
	}
};
haxecontracts_ContractException.__name__ = "haxecontracts.ContractException";
haxecontracts_ContractException.prototype = {
	toString: function() {
		var innerEx = this.innerException == null ? "" : ": " + Std.string(this.innerException);
		return this.message + (" (" + this.pos.fileName + ":" + this.pos.lineNumber + innerEx + ") ") + Std.string(this.arguments) + (this.object != null ? " " + Std.string(this.object) : "");
	}
	,__class__: haxecontracts_ContractException
};
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	if(Error.captureStackTrace) {
		Error.captureStackTrace(this,js__$Boot_HaxeError);
	}
};
js__$Boot_HaxeError.__name__ = "js._Boot.HaxeError";
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
	__class__: js__$Boot_HaxeError
});
var js_Boot = function() { };
js_Boot.__name__ = "js.Boot";
js_Boot.getClass = function(o) {
	if(o == null) {
		return null;
	} else if(((o) instanceof Array)) {
		return Array;
	} else {
		var cl = o.__class__;
		if(cl != null) {
			return cl;
		}
		var name = js_Boot.__nativeClassName(o);
		if(name != null) {
			return js_Boot.__resolveNativeClass(name);
		}
		return null;
	}
};
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o.__enum__) {
			var e = $hxEnums[o.__enum__];
			var n = e.__constructs__[o._hx_index];
			var con = e[n];
			if(con.__params__) {
				s = s + "\t";
				return n + "(" + ((function($this) {
					var $r;
					var _g = [];
					{
						var _g1 = 0;
						var _g2 = con.__params__;
						while(true) {
							if(!(_g1 < _g2.length)) {
								break;
							}
							var p = _g2[_g1];
							_g1 = _g1 + 1;
							_g.push(js_Boot.__string_rec(o[p],s));
						}
					}
					$r = _g;
					return $r;
				}(this))).join(",") + ")";
			} else {
				return n;
			}
		}
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g3 = 0;
			var _g11 = o.length;
			while(_g3 < _g11) {
				var i = _g3++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e1 ) {
			var e2 = ((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1;
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str1 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str1.length != 2) {
			str1 += ", \n";
		}
		str1 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str1 += "\n" + s + "}";
		return str1;
	case "string":
		return o;
	default:
		return String(o);
	}
};
js_Boot.__interfLoop = function(cc,cl) {
	if(cc == null) {
		return false;
	}
	if(cc == cl) {
		return true;
	}
	if(Object.prototype.hasOwnProperty.call(cc,"__interfaces__")) {
		var intf = cc.__interfaces__;
		var _g = 0;
		var _g1 = intf.length;
		while(_g < _g1) {
			var i = _g++;
			var i1 = intf[i];
			if(i1 == cl || js_Boot.__interfLoop(i1,cl)) {
				return true;
			}
		}
	}
	return js_Boot.__interfLoop(cc.__super__,cl);
};
js_Boot.__instanceof = function(o,cl) {
	if(cl == null) {
		return false;
	}
	switch(cl) {
	case Array:
		return ((o) instanceof Array);
	case Bool:
		return typeof(o) == "boolean";
	case Dynamic:
		return o != null;
	case Float:
		return typeof(o) == "number";
	case Int:
		if(typeof(o) == "number") {
			return ((o | 0) === o);
		} else {
			return false;
		}
		break;
	case String:
		return typeof(o) == "string";
	default:
		if(o != null) {
			if(typeof(cl) == "function") {
				if(js_Boot.__downcastCheck(o,cl)) {
					return true;
				}
			} else if(typeof(cl) == "object" && js_Boot.__isNativeObj(cl)) {
				if(((o) instanceof cl)) {
					return true;
				}
			}
		} else {
			return false;
		}
		if(cl == Class ? o.__name__ != null : false) {
			return true;
		}
		if(cl == Enum ? o.__ename__ != null : false) {
			return true;
		}
		return o.__enum__ != null ? $hxEnums[o.__enum__] == cl : false;
	}
};
js_Boot.__downcastCheck = function(o,cl) {
	if(!((o) instanceof cl)) {
		if(cl.__isInterface__) {
			return js_Boot.__interfLoop(js_Boot.getClass(o),cl);
		} else {
			return false;
		}
	} else {
		return true;
	}
};
js_Boot.__cast = function(o,t) {
	if(o == null || js_Boot.__instanceof(o,t)) {
		return o;
	} else {
		throw new js__$Boot_HaxeError("Cannot cast " + Std.string(o) + " to " + Std.string(t));
	}
};
js_Boot.__nativeClassName = function(o) {
	var name = js_Boot.__toStr.call(o).slice(8,-1);
	if(name == "Object" || name == "Function" || name == "Math" || name == "JSON") {
		return null;
	}
	return name;
};
js_Boot.__isNativeObj = function(o) {
	return js_Boot.__nativeClassName(o) != null;
};
js_Boot.__resolveNativeClass = function(name) {
	return $global[name];
};
var views__$HtmlElements_HtmlElements_$Impl_$ = {};
views__$HtmlElements_HtmlElements_$Impl_$.__name__ = "views._HtmlElements.HtmlElements_Impl_";
views__$HtmlElements_HtmlElements_$Impl_$.toElement = function(this1) {
	return window.document.querySelector("#" + this1);
};
var views_MainView = function(bookshelf,cardReader,workspace,itemScanner,screenView,printer) {
	this.bookshelf = bookshelf;
	this.workspace = workspace;
	this.cardReader = cardReader;
	this.itemScanner = itemScanner;
	this.screenView = screenView;
	this.printer = printer;
};
views_MainView.__name__ = "views.MainView";
views_MainView.__interfaces__ = [mithril_Mithril];
views_MainView.prototype = {
	mount: function() {
		m.mount(views__$HtmlElements_HtmlElements_$Impl_$.toElement("screen"),this.screenView);
		m.mount(views__$HtmlElements_HtmlElements_$Impl_$.toElement("printer"),this.printer);
		var f = $bind(this,this.surfaceView);
		var surface = this.bookshelf;
		var tmp = function() {
			return f(surface);
		};
		m.mount(views__$HtmlElements_HtmlElements_$Impl_$.toElement("bookshelf"),{ view : tmp});
		m.mount(views__$HtmlElements_HtmlElements_$Impl_$.toElement("card-reader"),{ view : $bind(this,this.cardReaderView)});
		var f1 = $bind(this,this.surfaceView);
		var surface1 = this.itemScanner;
		var tmp1 = function() {
			return f1(surface1);
		};
		m.mount(views__$HtmlElements_HtmlElements_$Impl_$.toElement("scanner"),{ view : tmp1});
		var f2 = $bind(this,this.surfaceView);
		var surface2 = this.workspace;
		var tmp2 = function() {
			return f2(surface2);
		};
		m.mount(views__$HtmlElements_HtmlElements_$Impl_$.toElement("workspace"),{ view : tmp2});
	}
	,surfaceView: function(surface) {
		var result = new Array(surface.length);
		var _g = 0;
		var _g1 = surface.length;
		while(_g < _g1) {
			var i = _g++;
			var item = surface[i];
			var tmp;
			var _g2 = js_Boot.getClass(item);
			switch(_g2) {
			case Bluray:
				var item1 = item;
				tmp = m.m(".bluray.cover",item1.title);
				break;
			case Book:
				var item2 = item;
				tmp = m.m(".book.cover",item2.title);
				break;
			case LibraryCard:
				tmp = m.m("img.card[src=images/card.svg]");
				break;
			default:
				var unknown = _g2;
				var tmp1 = "View not found for: " + unknown.__name__;
				tmp = m.m("div",{ style : "color:red"},tmp1);
			}
			result[i] = tmp;
		}
		return result;
	}
	,cardReaderView: function() {
		if(this.cardReader.length == 0) {
			return m.m("div","Card reader");
		} else {
			var _g = js_Boot.getClass(this.cardReader[0]);
			if(_g == LibraryCard) {
				return m.m("img.card[src=images/card.svg]");
			} else {
				var unknown = _g;
				var tmp = "View not found for: " + unknown.__name__;
				return m.m("div",{ style : "color:red"},tmp);
			}
		}
	}
	,__class__: views_MainView
};
var views_ScreenState = $hxEnums["views.ScreenState"] = { __ename__ : true, __constructs__ : ["Welcome","EnterPin","DisplayBorrowedItems","ThankYou","TooManyInvalidPin","InvalidCard","InvalidLoanItem","ItemAlreadyBorrowed","DontForgetLibraryCard"]
	,Welcome: {_hx_index:0,__enum__:"views.ScreenState",toString:$estr}
	,EnterPin: ($_=function(data) { return {_hx_index:1,data:data,__enum__:"views.ScreenState",toString:$estr}; },$_.__params__ = ["data"],$_)
	,DisplayBorrowedItems: ($_=function(scannedItems) { return {_hx_index:2,scannedItems:scannedItems,__enum__:"views.ScreenState",toString:$estr}; },$_.__params__ = ["scannedItems"],$_)
	,ThankYou: {_hx_index:3,__enum__:"views.ScreenState",toString:$estr}
	,TooManyInvalidPin: {_hx_index:4,__enum__:"views.ScreenState",toString:$estr}
	,InvalidCard: {_hx_index:5,__enum__:"views.ScreenState",toString:$estr}
	,InvalidLoanItem: {_hx_index:6,__enum__:"views.ScreenState",toString:$estr}
	,ItemAlreadyBorrowed: {_hx_index:7,__enum__:"views.ScreenState",toString:$estr}
	,DontForgetLibraryCard: {_hx_index:8,__enum__:"views.ScreenState",toString:$estr}
};
var views_ScreenView = function() {
	this._onFinishWithReceiptClicked = new SingleEventHandler();
	this._onFinishWithoutReceiptClicked = new SingleEventHandler();
	this._onPinCodeEntered = new SingleEventHandler();
	this.pinBuffer = "";
	this.messageTimer = new haxe_Timer(1000);
	this.currentState = views_ScreenState.Welcome;
};
views_ScreenView.__name__ = "views.ScreenView";
views_ScreenView.__interfaces__ = [mithril_Mithril,haxecontracts_HaxeContracts];
views_ScreenView.prototype = {
	display: function(state) {
		this.messageTimer.stop();
		this.currentState = state;
		m.redraw();
		try {
			if(this.currentState == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [currentState != null]",this,[state],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 77, className : "views.ScreenView", methodName : "display"}));
			}
		} catch( e ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [currentState != null]",this,[state],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "src/views/ScreenView.hx", lineNumber : 77, className : "views.ScreenView", methodName : "display"}));
		}
		try {
			if(this.pinBuffer == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [pinBuffer != null]",this,[state],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 78, className : "views.ScreenView", methodName : "display"}));
			}
		} catch( e1 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [pinBuffer != null]",this,[state],((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1,{ fileName : "src/views/ScreenView.hx", lineNumber : 78, className : "views.ScreenView", methodName : "display"}));
		}
		try {
			if(this.messageTimer == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [messageTimer != null]",this,[state],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 79, className : "views.ScreenView", methodName : "display"}));
			}
		} catch( e2 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [messageTimer != null]",this,[state],((e2) instanceof js__$Boot_HaxeError) ? e2.val : e2,{ fileName : "src/views/ScreenView.hx", lineNumber : 79, className : "views.ScreenView", methodName : "display"}));
		}
	}
	,displayMessage: function(state,waitMs,thenDisplay) {
		try {
			if(waitMs <= 0) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [waitMs > 0]",this,[state,waitMs,thenDisplay],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 48, className : "views.ScreenView", methodName : "displayMessage"}));
			}
		} catch( e ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [waitMs > 0]",this,[state,waitMs,thenDisplay],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "src/views/ScreenView.hx", lineNumber : 48, className : "views.ScreenView", methodName : "displayMessage"}));
		}
		if(thenDisplay == null) {
			thenDisplay = this.currentState;
		}
		this.display(state);
		this.messageTimer = new haxe_Timer(waitMs);
		var f = $bind(this,this.display);
		var state1 = thenDisplay;
		var tmp = function() {
			f(state1);
		};
		this.messageTimer.run = tmp;
		try {
			if(this.currentState == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [currentState != null]",this,[state,waitMs,thenDisplay],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 77, className : "views.ScreenView", methodName : "displayMessage"}));
			}
		} catch( e1 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [currentState != null]",this,[state,waitMs,thenDisplay],((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1,{ fileName : "src/views/ScreenView.hx", lineNumber : 77, className : "views.ScreenView", methodName : "displayMessage"}));
		}
		try {
			if(this.pinBuffer == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [pinBuffer != null]",this,[state,waitMs,thenDisplay],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 78, className : "views.ScreenView", methodName : "displayMessage"}));
			}
		} catch( e2 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [pinBuffer != null]",this,[state,waitMs,thenDisplay],((e2) instanceof js__$Boot_HaxeError) ? e2.val : e2,{ fileName : "src/views/ScreenView.hx", lineNumber : 78, className : "views.ScreenView", methodName : "displayMessage"}));
		}
		try {
			if(this.messageTimer == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [messageTimer != null]",this,[state,waitMs,thenDisplay],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 79, className : "views.ScreenView", methodName : "displayMessage"}));
			}
		} catch( e3 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [messageTimer != null]",this,[state,waitMs,thenDisplay],((e3) instanceof js__$Boot_HaxeError) ? e3.val : e3,{ fileName : "src/views/ScreenView.hx", lineNumber : 79, className : "views.ScreenView", methodName : "displayMessage"}));
		}
	}
	,onPinCodeEntered: function(callback,pos) {
		try {
			if(callback == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [callback != null]",this,[callback,pos],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 60, className : "views.ScreenView", methodName : "onPinCodeEntered"}));
			}
		} catch( e ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [callback != null]",this,[callback,pos],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "src/views/ScreenView.hx", lineNumber : 60, className : "views.ScreenView", methodName : "onPinCodeEntered"}));
		}
		this._onPinCodeEntered.set(callback,pos);
		try {
			if(this.currentState == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [currentState != null]",this,[callback,pos],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 77, className : "views.ScreenView", methodName : "onPinCodeEntered"}));
			}
		} catch( e1 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [currentState != null]",this,[callback,pos],((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1,{ fileName : "src/views/ScreenView.hx", lineNumber : 77, className : "views.ScreenView", methodName : "onPinCodeEntered"}));
		}
		try {
			if(this.pinBuffer == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [pinBuffer != null]",this,[callback,pos],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 78, className : "views.ScreenView", methodName : "onPinCodeEntered"}));
			}
		} catch( e2 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [pinBuffer != null]",this,[callback,pos],((e2) instanceof js__$Boot_HaxeError) ? e2.val : e2,{ fileName : "src/views/ScreenView.hx", lineNumber : 78, className : "views.ScreenView", methodName : "onPinCodeEntered"}));
		}
		try {
			if(this.messageTimer == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [messageTimer != null]",this,[callback,pos],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 79, className : "views.ScreenView", methodName : "onPinCodeEntered"}));
			}
		} catch( e3 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [messageTimer != null]",this,[callback,pos],((e3) instanceof js__$Boot_HaxeError) ? e3.val : e3,{ fileName : "src/views/ScreenView.hx", lineNumber : 79, className : "views.ScreenView", methodName : "onPinCodeEntered"}));
		}
	}
	,onFinishWithoutReceiptClicked: function(callback,pos) {
		try {
			if(callback == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [callback != null]",this,[callback,pos],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 65, className : "views.ScreenView", methodName : "onFinishWithoutReceiptClicked"}));
			}
		} catch( e ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [callback != null]",this,[callback,pos],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "src/views/ScreenView.hx", lineNumber : 65, className : "views.ScreenView", methodName : "onFinishWithoutReceiptClicked"}));
		}
		this._onFinishWithoutReceiptClicked.set(callback,pos);
		try {
			if(this.currentState == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [currentState != null]",this,[callback,pos],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 77, className : "views.ScreenView", methodName : "onFinishWithoutReceiptClicked"}));
			}
		} catch( e1 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [currentState != null]",this,[callback,pos],((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1,{ fileName : "src/views/ScreenView.hx", lineNumber : 77, className : "views.ScreenView", methodName : "onFinishWithoutReceiptClicked"}));
		}
		try {
			if(this.pinBuffer == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [pinBuffer != null]",this,[callback,pos],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 78, className : "views.ScreenView", methodName : "onFinishWithoutReceiptClicked"}));
			}
		} catch( e2 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [pinBuffer != null]",this,[callback,pos],((e2) instanceof js__$Boot_HaxeError) ? e2.val : e2,{ fileName : "src/views/ScreenView.hx", lineNumber : 78, className : "views.ScreenView", methodName : "onFinishWithoutReceiptClicked"}));
		}
		try {
			if(this.messageTimer == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [messageTimer != null]",this,[callback,pos],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 79, className : "views.ScreenView", methodName : "onFinishWithoutReceiptClicked"}));
			}
		} catch( e3 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [messageTimer != null]",this,[callback,pos],((e3) instanceof js__$Boot_HaxeError) ? e3.val : e3,{ fileName : "src/views/ScreenView.hx", lineNumber : 79, className : "views.ScreenView", methodName : "onFinishWithoutReceiptClicked"}));
		}
	}
	,onFinishWithReceiptClicked: function(callback,pos) {
		try {
			if(callback == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [callback != null]",this,[callback,pos],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 70, className : "views.ScreenView", methodName : "onFinishWithReceiptClicked"}));
			}
		} catch( e ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [callback != null]",this,[callback,pos],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "src/views/ScreenView.hx", lineNumber : 70, className : "views.ScreenView", methodName : "onFinishWithReceiptClicked"}));
		}
		this._onFinishWithReceiptClicked.set(callback,pos);
		try {
			if(this.currentState == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [currentState != null]",this,[callback,pos],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 77, className : "views.ScreenView", methodName : "onFinishWithReceiptClicked"}));
			}
		} catch( e1 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [currentState != null]",this,[callback,pos],((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1,{ fileName : "src/views/ScreenView.hx", lineNumber : 77, className : "views.ScreenView", methodName : "onFinishWithReceiptClicked"}));
		}
		try {
			if(this.pinBuffer == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [pinBuffer != null]",this,[callback,pos],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 78, className : "views.ScreenView", methodName : "onFinishWithReceiptClicked"}));
			}
		} catch( e2 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [pinBuffer != null]",this,[callback,pos],((e2) instanceof js__$Boot_HaxeError) ? e2.val : e2,{ fileName : "src/views/ScreenView.hx", lineNumber : 78, className : "views.ScreenView", methodName : "onFinishWithReceiptClicked"}));
		}
		try {
			if(this.messageTimer == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [messageTimer != null]",this,[callback,pos],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 79, className : "views.ScreenView", methodName : "onFinishWithReceiptClicked"}));
			}
		} catch( e3 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [messageTimer != null]",this,[callback,pos],((e3) instanceof js__$Boot_HaxeError) ? e3.val : e3,{ fileName : "src/views/ScreenView.hx", lineNumber : 79, className : "views.ScreenView", methodName : "onFinishWithReceiptClicked"}));
		}
	}
	,view: function() {
		if(arguments.length > 0 && arguments[0].tag != this) return arguments[0].tag.view.apply(arguments[0].tag, arguments);
		try {
			if(this.currentState == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [currentState != null]",this,[],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 77, className : "views.ScreenView", methodName : "view"}));
			}
		} catch( e ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [currentState != null]",this,[],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "src/views/ScreenView.hx", lineNumber : 77, className : "views.ScreenView", methodName : "view"}));
		}
		try {
			if(this.pinBuffer == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [pinBuffer != null]",this,[],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 78, className : "views.ScreenView", methodName : "view"}));
			}
		} catch( e1 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [pinBuffer != null]",this,[],((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1,{ fileName : "src/views/ScreenView.hx", lineNumber : 78, className : "views.ScreenView", methodName : "view"}));
		}
		try {
			if(this.messageTimer == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [messageTimer != null]",this,[],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 79, className : "views.ScreenView", methodName : "view"}));
			}
		} catch( e2 ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract invariant failed for: [messageTimer != null]",this,[],((e2) instanceof js__$Boot_HaxeError) ? e2.val : e2,{ fileName : "src/views/ScreenView.hx", lineNumber : 79, className : "views.ScreenView", methodName : "view"}));
		}
		var __contract_output;
		var _g = this.currentState;
		switch(_g._hx_index) {
		case 0:
			__contract_output = this.welcome();
			break;
		case 1:
			var data = _g.data;
			__contract_output = this.enterPin(data.previousAttemptFailed);
			break;
		case 2:
			var scannedItems = _g.scannedItems;
			__contract_output = this.displayBorrowedItems(scannedItems);
			break;
		case 3:
			__contract_output = this.thankYou();
			break;
		case 4:
			__contract_output = this.tooManyInvalidPin();
			break;
		case 5:
			__contract_output = this.invalidCard();
			break;
		case 6:
			__contract_output = this.invalidLoanItem();
			break;
		case 7:
			__contract_output = this.itemAlreadyBorrowed();
			break;
		case 8:
			__contract_output = this.dontForgetLibraryCard();
			break;
		}
		return __contract_output;
	}
	,welcome: function() {
		return m.m(".content",[m.m("p","Welcome to the library borrowing machine!"),m.m("p",m.m("strong","Please drag your card to the reader.")),m.m("p","Books are available on the top shelf.")]);
	}
	,enterPin: function(previousAttemptFailed) {
		var _gthis = this;
		var tmp = m.m(".content",previousAttemptFailed ? m.m(".red","Incorrect PIN. Enter your 4-digit PIN.") : m.m("p","Enter your 4-digit PIN."));
		var tmp1 = m.m(".content",m.m("p",this.pinBuffer.length == 0 ? m.trust("&nbsp;") : StringTools.rpad("","*",this.pinBuffer.length)));
		var _this = ["1","2","3","4","5","6","7","8","9","0"];
		var result = new Array(_this.length);
		var _g = 0;
		var _g1 = _this.length;
		while(_g < _g1) {
			var i = _g++;
			var key = _this[i];
			result[i] = m.m(".key",{ onclick : (function(key1,f) {
				return function() {
					f[0](key1[0]);
				};
			})([key],[$bind(_gthis,_gthis.enterPinKeyPressed)])},key);
		}
		return [tmp,tmp1,m.m(".content.keypad",result)];
	}
	,enterPinKeyPressed: function(key) {
		this.pinBuffer += key;
		if(this.pinBuffer.length < 4) {
			return;
		}
		var pin = this.pinBuffer;
		this.pinBuffer = "";
		(this._onPinCodeEntered.get_trigger())(pin);
	}
	,tooManyInvalidPin: function() {
		return m.m(".content",[m.m(".red","Incorrect PIN too many times."),m.m("p","Please remove your card before trying again.")]);
	}
	,displayBorrowedItems: function(scannedItems) {
		var _gthis = this;
		try {
			if(scannedItems == null) {
				throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [scannedItems != null]",this,[scannedItems],null,{ fileName : "src/views/ScreenView.hx", lineNumber : 152, className : "views.ScreenView", methodName : "displayBorrowedItems"}));
			}
		} catch( e ) {
			throw new js__$Boot_HaxeError(new haxecontracts_ContractException("Contract precondition failed for: [scannedItems != null]",this,[scannedItems],((e) instanceof js__$Boot_HaxeError) ? e.val : e,{ fileName : "src/views/ScreenView.hx", lineNumber : 152, className : "views.ScreenView", methodName : "displayBorrowedItems"}));
		}
		var tmp = m.m("p","Scan the items you want to borrow on the dark red area.");
		var tmp1 = m.m("p",[m.m("button.-success",{ style : "margin-right:2px", onclick : function() {
			(_gthis._onFinishWithReceiptClicked.get_trigger())();
		}},"Finish with receipt"),m.m("button.-success",{ onclick : function() {
			(_gthis._onFinishWithoutReceiptClicked.get_trigger())();
		}},"Finish without receipt")]);
		var tmp2 = m.m("thead",m.m("tr",[m.m("th","Title"),m.m("th","Return date")]));
		var _g7 = [];
		var scanned = $getIterator(scannedItems);
		while(scanned.hasNext()) {
			var scanned1 = scanned.next();
			_g7.push(m.m("tr",[m.m("td",scanned1.item.title),m.m("td",DateTools.format(scanned1.returnDate,"%Y-%m-%d"))]));
		}
		return m.m(".content",[tmp,tmp1,m.m("table",[tmp2,m.m("tbody",_g7)])]);
	}
	,invalidCard: function() {
		return m.m(".content",[m.m(".red","Library card not valid."),m.m("p","Please contact support.")]);
	}
	,thankYou: function() {
		return m.m(".content",[m.m("p","Thank you for using the automatic borrowing service!")]);
	}
	,dontForgetLibraryCard: function() {
		return m.m(".content",[m.m("p",m.m("strong","Don't forget your library card!"))]);
	}
	,invalidLoanItem: function() {
		return m.m(".content",[m.m(".red","Loan item not valid."),m.m("p","Please contact support.")]);
	}
	,itemAlreadyBorrowed: function() {
		return m.m(".content",[m.m(".red","Loan item already borrowed."),m.m("p","Please contact support.")]);
	}
	,__class__: views_ScreenView
};
function $getIterator(o) { if( o instanceof Array ) return HxOverrides.iter(o); else return o.iterator(); }
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $global.$haxeUID++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
$global.$haxeUID |= 0;
String.prototype.__class__ = String;
String.__name__ = "String";
Array.__name__ = "Array";
Date.prototype.__class__ = Date;
Date.__name__ = "Date";
var Int = { };
var Dynamic = { };
var Float = Number;
var Bool = Boolean;
var Class = { };
var Enum = { };
var __map_reserved = {};
Object.defineProperty(js__$Boot_HaxeError.prototype,"message",{ get : function() {
	return String(this.val);
}});
js_Boot.__toStr = ({ }).toString;
try {
var __varName = window.m;
(function(m) {
			if (m.m) return;
			m.m = function() {
				try { 
					for(var i=0; i < arguments.length; ++i) if(arguments[i] instanceof List) {
						var list = arguments[i].h; arguments[i] = [];
						while(list != null) { arguments[i].push(l[0]); list = l[1]; }
					}
				} catch(e) {}
				return m.apply(this, arguments);
			}
		})(__varName);
} catch(_) {}
try {
global.m = require("mithril");
var __varName1 = global.m;
(function(m) {
			if (m.m) return;
			m.m = function() {
				try { 
					for(var i=0; i < arguments.length; ++i) if(arguments[i] instanceof List) {
						var list = arguments[i].h; arguments[i] = [];
						while(list != null) { arguments[i].push(l[0]); list = l[1]; }
					}
				} catch(e) {}
				return m.apply(this, arguments);
			}
		})(__varName1);
} catch(_) {}
DateTools.DAY_SHORT_NAMES = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
DateTools.DAY_NAMES = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
DateTools.MONTH_SHORT_NAMES = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
DateTools.MONTH_NAMES = ["January","February","March","April","May","June","July","August","September","October","November","December"];
contexts_BorrowLoanItem.__meta__ = { fields : { librarian : { role : null}, listOfLoans : { role : null}, listOfLibraryCards : { role : null}, listOfItems : { role : null}, loanItem : { role : null}, borrower : { role : null}}};
contexts_LibraryBorrowMachine.__meta__ = { fields : { cardReader : { role : null}, scanner : { role : null}, scannedItems : { role : null}, screen : { role : null}, finishButtons : { role : null}, keypad : { role : null}, printer : { role : null}, library : { role : null}}};
contexts_LibraryBorrowMachine.maxPinAttempts = 3;
haxecontracts_Contract.implementationError = "A class calling haxecontracts.Contract must implement haxecontracts.HaxeContracts";
views__$HtmlElements_HtmlElements_$Impl_$.Bookshelf = "bookshelf";
views__$HtmlElements_HtmlElements_$Impl_$.Printer = "printer";
views__$HtmlElements_HtmlElements_$Impl_$.Screen = "screen";
views__$HtmlElements_HtmlElements_$Impl_$.CardReader = "card-reader";
views__$HtmlElements_HtmlElements_$Impl_$.Workspace = "workspace";
views__$HtmlElements_HtmlElements_$Impl_$.Scanner = "scanner";
Main.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);

//# sourceMappingURL=haxedci-example.js.map